theory Bacon_Source_Named_Reverse_Model
  imports Bacon_Source_Erased_Structure Bacon_Source_Erased_Locality
    Bacon_Source_Erased_Truth Bacon_Source_Named_Model_Type_Tagging_Model
begin

section \<open>Constructing a finite-frame model from every named model\<close>

text \<open>
  A named BBK model on D′σ = {⟨σ,a⟩ | a ∈ Dσ} induces a
  finite-frame BBK structure with the same domains and valuation and
  the context-free interpretation named_erased_denote. All structural
  and six truth clauses are proved, including locality across different
  typing frames. Source: Bacon–Dorr Definition 3.1, pp.43–44.

  Every independent named model has a proved truth-preserving tagged copy.
  Applying the first construction to that copy gives the general reverse
  model theorem below. No restriction to named models generated by the
  earlier forward interpretation is made.

  Status: model construction, not yet the named-H proof correspondence or
  an isomorphism recovering all original semantic values. The carrier
  changes explicitly to otype × value. Truth transport for translated
  formulas and source-language completeness remain separate theorems.
\<close>

theorem paper_tagged_named_to_db_model:
  assumes model: "paper_named_bbk_model \<Sigma> G (named_tag_domain D) J V"
  shows "paper_db_bbk_structure \<Sigma> (named_tag_domain D) (named_erased_denote G J) V"
proof -
  interpret Named: paper_named_bbk_model \<Sigma> G "named_tag_domain D" J V by (rule model)
  show ?thesis
    apply unfold_locales
               apply (rule Named.domain_nonempty)
              apply (rule named_erased_denote_type[OF model]; assumption)
             apply (rule named_erased_denote_var[OF model]; assumption)
            apply (rule named_erased_denote_application[OF model]; assumption)
           apply (rule named_erased_denote_locality[OF model]; assumption)
          apply (rule named_erased_denote_conversion[OF model]; assumption)
         apply (rule erased_valuation_neg[OF model]; assumption)
        apply (rule erased_valuation_conj[OF model]; assumption)
       apply (rule erased_valuation_disj[OF model]; assumption)
      apply (rule erased_valuation_forall[OF model]; assumption)
     apply (rule erased_valuation_exists[OF model]; assumption)
    apply (rule erased_valuation_identity[OF model]; assumption)
    done
qed

context paper_named_bbk_model
begin

theorem paper_named_to_db_model:
  "paper_db_bbk_structure signature (named_tag_domain domain)
    (named_erased_denote stock model_tag_denote) model_tag_valuation"
  by (rule paper_tagged_named_to_db_model[OF model_type_tagging])

end

end
