theory Bacon_Source_Relational_Classicism_BBK_Soundness
  imports Bacon_Source_Relational_Classicism_Presentation Bacon_Source_Relational_H_Soundness
begin

section \<open>The smallest H-theory generated by Logical Equivalence is sound\<close>

text \<open>
  C is the smallest H-theory containing Logical Equivalence:
  (λv⃗.P)=(λv⃗.Q) whenever ⊢H P↔Q. Source: §1.3, p.12.
  In a supplied independent R-BBK model, assume validity of precisely
  these H-certified instances. A direct induction on the five native
  constructors then proves validity of every C theorem.

  The extra premise does NOT assert soundness of the general
  Equivalence rule: its certificate is native R-H theoremhood, never
  recursive C theoremhood or arbitrary semantic equivalence. The
  original R model supplies H soundness and MP/Gen/Inst closure.
  No F model, category premise, presentation equivalence, or model
  existence theorem is used. An empty or repeated-name vector is
  allowed exactly as in the native Logical Equivalence constructor.
\<close>

context paper_R_bbk_model
begin

theorem paper_R_classicism_BBK_soundness:
  assumes logical_equivalence: "\<And>P Q ns.
      paper_R_named_H signature stock (named_paper_iff stock P Q) \<Longrightarrow>
      paper_R_in_language signature stock P Prop \<Longrightarrow>
      paper_R_in_language signature stock Q Prop \<Longrightarrow>
      list_all paper_R_type (map stock ns) \<Longrightarrow>
      paper_R_valid (named_paper_eq (paper_type_vector (map stock ns) Prop)
        (named_lam_vec ns P) (named_lam_vec ns Q))"
    and derivation: "paper_R_classicism_proves signature stock A"
  shows "paper_R_valid A"
  using derivation
proof (induction rule: paper_R_classicism_proves.induct)
  case H
  show ?case by (rule paper_R_named_H_soundness[OF H.hyps])
next
  case Logical_Equivalence
  show ?case by (rule logical_equivalence[OF Logical_Equivalence.hyps])
next
  case MP
  show ?case by (rule paper_R_valid_MP[
    OF paper_R_valid_language[OF MP.IH(1)] MP.hyps(3) MP.IH(1,2)])
next
  case (Gen P Q n \<sigma>)
  have operands: "paper_R_in_language signature stock P Prop \<and>
    paper_R_in_language signature stock Q Prop"
    by (rule paper_R_imp_language_operands[OF stock_rich paper_R_valid_language[OF Gen.IH]])
  have quantifier: "paper_R_in_language signature stock (named_paper_all \<sigma> (NLam n Q)) Prop"
    by (rule conjunct2[OF paper_R_imp_language_operands[OF stock_rich Gen.hyps(4)]])
  have predicate: "paper_R_in_language signature stock (NLam n Q) (Arr \<sigma> Prop)"
    by (rule paper_R_all_language_operand[OF quantifier])
  have rt: "paper_R_type \<sigma>"
    by (rule paper_R_arrow_domain[OF paper_R_language_result_type[OF predicate]])
  show ?case by (rule paper_R_valid_Gen[
    OF conjunct1[OF operands] conjunct2[OF operands] Gen.hyps(2) rt Gen.hyps(3) Gen.IH])
next
  case (Inst P Q n \<sigma>)
  have operands: "paper_R_in_language signature stock P Prop \<and>
    paper_R_in_language signature stock Q Prop"
    by (rule paper_R_imp_language_operands[OF stock_rich paper_R_valid_language[OF Inst.IH]])
  have quantifier: "paper_R_in_language signature stock (named_paper_ex \<sigma> (NLam n P)) Prop"
    by (rule conjunct1[OF paper_R_imp_language_operands[OF stock_rich Inst.hyps(4)]])
  have predicate: "paper_R_in_language signature stock (NLam n P) (Arr \<sigma> Prop)"
    by (rule paper_R_ex_language_operand[OF quantifier])
  have rt: "paper_R_type \<sigma>"
    by (rule paper_R_arrow_domain[OF paper_R_language_result_type[OF predicate]])
  show ?case by (rule paper_R_valid_Inst[
    OF conjunct1[OF operands] conjunct2[OF operands] Inst.hyps(2) rt Inst.hyps(3) Inst.IH])
qed

end

end
