theory Bacon_Source_Relational_Conversion
  imports Bacon_Source_Relational_Syntax
    Bacon_Source_Vocabulary_Development.Bacon_Source_Named_Raw_Conversion
begin

section \<open>Raw conversion through R terms\<close>

text \<open>
  A≡βηB at σ∈R is generated by contextual β and η, with every
  intermediate term R-typed in the same stock G. Source: Bacon–Dorr
  §1.1, p.5, Figure 2, p.8, and Definition 3.1(ii.d), p.44.
  The model clause separately guards the two endpoints by ℒ(Σ).

  Representation: paper_R_raw_beta_eta has no signature parameter and
  no α constructor. Its β/η steps are the existing literal named steps,
  but its typing guards are paper_R_has_type. Status: only the forward
  embedding into F conversion is proved; no converse or conservativity
  theorem is asserted.
\<close>

inductive paper_R_raw_beta_eta ::
  "sgcontext \<Rightarrow> otype \<Rightarrow> 'c paper_named_term \<Rightarrow> 'c paper_named_term \<Rightarrow> bool"
  for G :: sgcontext where
  Refl: "paper_R_has_type G A \<tau> \<Longrightarrow> paper_R_raw_beta_eta G \<tau> A A"
| Beta: "paper_R_has_type G A \<tau> \<Longrightarrow> paper_R_has_type G B \<tau> \<Longrightarrow>
    named_compatible_step named_beta_contract A B \<Longrightarrow> paper_R_raw_beta_eta G \<tau> A B"
| Eta: "paper_R_has_type G A \<tau> \<Longrightarrow> paper_R_has_type G B \<tau> \<Longrightarrow>
    named_compatible_step named_eta_contract A B \<Longrightarrow> paper_R_raw_beta_eta G \<tau> A B"
| Sym: "paper_R_raw_beta_eta G \<tau> A B \<Longrightarrow> paper_R_raw_beta_eta G \<tau> B A"
| Trans: "paper_R_raw_beta_eta G \<tau> A B \<Longrightarrow> paper_R_raw_beta_eta G \<tau> B C \<Longrightarrow>
    paper_R_raw_beta_eta G \<tau> A C"

lemma paper_R_raw_beta_eta_types:
  assumes "paper_R_raw_beta_eta G \<tau> A B"
  shows "paper_R_has_type G A \<tau> \<and> paper_R_has_type G B \<tau>"
  using assms by (induction rule: paper_R_raw_beta_eta.induct) blast+

lemma paper_R_raw_beta_eta_result_type:
  assumes "paper_R_raw_beta_eta G \<tau> A B"
  shows "paper_R_type \<tau>"
  using paper_R_raw_beta_eta_types[OF assms] by (blast intro: paper_R_result_type)

lemma paper_R_type_universal_language:
  assumes "paper_R_has_type G A \<tau>"
  shows "named_in_language paper_logical_type (\<lambda>_. UNIV) G A \<tau>"
  using paper_R_has_type_embedding[OF assms] by (simp only: named_universal_language)

theorem paper_R_raw_beta_eta_embedding:
  assumes "paper_R_raw_beta_eta G \<tau> A B"
  shows "named_raw_beta_eta paper_logical_type G \<tau> A B"
  using assms
proof (induction rule: paper_R_raw_beta_eta.induct)
  case Refl
  show ?case
    by (rule named_beta_eta_in_language.Refl[OF paper_R_type_universal_language[OF Refl.hyps]])
next
  case Beta
  show ?case by (rule named_beta_eta_in_language.Beta[
    OF paper_R_type_universal_language[OF Beta.hyps(1)]
      paper_R_type_universal_language[OF Beta.hyps(2)] Beta.hyps(3)])
next
  case Eta
  show ?case by (rule named_beta_eta_in_language.Eta[
    OF paper_R_type_universal_language[OF Eta.hyps(1)]
      paper_R_type_universal_language[OF Eta.hyps(2)] Eta.hyps(3)])
next
  case Sym
  show ?case by (rule named_beta_eta_in_language.Sym[OF Sym.IH])
next
  case Trans
  show ?case by (rule named_beta_eta_in_language.Trans[OF Trans.IH])
qed

end
