theory Bacon_PP_ZF_Exact_Logical_Stock
  imports 
    "Goodman_Exact_Legacy_04.Bacon_PP_ZF_Exact_Frame"
begin

section \<open>The least admissible stock generated by closed logical terms\<close>

definition pp_e_closed_den :: "oterm \<Rightarrow> ZF" where
  "pp_e_closed_den M =
    pp_e_eval pp_e_default_constants pp_e_closed_env M"

lemma pp_e_eval_const_free:
  assumes "consts_of M = {}"
  shows "pp_e_eval C \<rho> M = pp_e_eval D \<rho> M"
  using assms
proof (induction M arbitrary: \<rho>)
  case (Var n)
  then show ?case by simp
next
  case (Const c \<sigma>)
  then show ?case by simp
next
  case (App M N)
  then show ?case by simp
next
  case (Lam \<sigma> M)
  then show ?case by simp
next
  case (Eq \<sigma> M N)
  then show ?case by simp
next
  case (Neg M)
  then show ?case by simp
next
  case (Conj M N)
  then show ?case by simp
next
  case (Disj M N)
  then show ?case by simp
next
  case (Imp M N)
  then show ?case by simp
next
  case (Forall \<sigma> M)
  then show ?case by simp
next
  case (Exists \<sigma> M)
  then show ?case by simp
qed

lemma pp_e_closed_den_in_domain:
  assumes typed: "[] \<turnstile> M : \<sigma>"
  shows "Elem (pp_e_closed_den M) (pp_e_domain \<sigma>)"
  unfolding pp_e_closed_den_def
  using DefaultExactBaconConstants.pp_e_eval_type[
    OF typed pp_e_empty_env_typed]
  by (simp add: pp_e_dom_def)

definition pp_e_closed_logical_stock ::
    "otype \<Rightarrow> nat list \<Rightarrow> ZF \<Rightarrow> bool"
  where
  "pp_e_closed_logical_stock \<sigma> w x \<longleftrightarrow>
    Elem x (pp_e_domain \<sigma>) \<and>
    (\<exists>M.
      [] \<turnstile> M : \<sigma> \<and>
      pp_logical_vocabulary M \<and>
      pp_e_eqv \<sigma> w x (pp_e_closed_den M))"

lemma pp_e_closed_logical_stockI:
  assumes typed: "[] \<turnstile> M : \<sigma>"
    and logical: "pp_logical_vocabulary M"
  shows "pp_e_closed_logical_stock \<sigma> w (pp_e_closed_den M)"
proof -
  have domain: "Elem (pp_e_closed_den M) (pp_e_domain \<sigma>)"
    using pp_e_closed_den_in_domain[OF typed] .
  have refl:
      "pp_e_eqv \<sigma> w (pp_e_closed_den M) (pp_e_closed_den M)"
    using pp_e_eqv_reflexive[OF domain] .
  show ?thesis
    unfolding pp_e_closed_logical_stock_def
    using domain typed logical refl by blast
qed

lemma pp_e_closed_logical_stock_persistent:
  assumes stock: "pp_e_closed_logical_stock \<sigma> w x"
    and future: "prefix w v"
  shows "pp_e_closed_logical_stock \<sigma> v x"
proof -
  obtain M where x: "Elem x (pp_e_domain \<sigma>)"
    and typed: "[] \<turnstile> M : \<sigma>"
    and logical: "pp_logical_vocabulary M"
    and xM: "pp_e_eqv \<sigma> w x (pp_e_closed_den M)"
    using stock unfolding pp_e_closed_logical_stock_def by blast
  have xM_v:
      "pp_e_eqv \<sigma> v x (pp_e_closed_den M)"
    using pp_e_eqv_persistent[OF xM future] .
  show ?thesis
    unfolding pp_e_closed_logical_stock_def
    using x typed logical xM_v by blast
qed

lemma pp_e_closed_logical_stock_all_worlds_iff_root:
  "(\<forall>w. pp_e_closed_logical_stock \<sigma> w x)
    \<longleftrightarrow>
    pp_e_closed_logical_stock \<sigma> [] x"
proof
  assume all: "\<forall>w. pp_e_closed_logical_stock \<sigma> w x"
  show "pp_e_closed_logical_stock \<sigma> [] x"
    using all by blast
next
  assume root: "pp_e_closed_logical_stock \<sigma> [] x"
  show "\<forall>w. pp_e_closed_logical_stock \<sigma> w x"
  proof
    fix w
    show "pp_e_closed_logical_stock \<sigma> w x"
      using pp_e_closed_logical_stock_persistent[
        OF root, of w] by simp
  qed
qed

lemma pp_e_closed_logical_stock_admissible:
  "pp_e_predicate_admissible \<sigma>
    (pp_e_closed_logical_stock \<sigma>)"
proof (unfold pp_e_predicate_admissible_def, intro allI impI)
  fix w x y v
  assume x: "Elem x (pp_e_domain \<sigma>)"
    and y: "Elem y (pp_e_domain \<sigma>)"
    and xy: "pp_e_eqv \<sigma> w x y"
    and future: "prefix w v"
  have xy_v: "pp_e_eqv \<sigma> v x y"
    using pp_e_eqv_persistent[OF xy future] .
  have yx_v: "pp_e_eqv \<sigma> v y x"
    using pp_e_eqv_symmetric[OF x y xy_v] .
  show "pp_e_closed_logical_stock \<sigma> v x =
      pp_e_closed_logical_stock \<sigma> v y"
  proof
    assume stock_x: "pp_e_closed_logical_stock \<sigma> v x"
    then obtain M where typed: "[] \<turnstile> M : \<sigma>"
      and logical: "pp_logical_vocabulary M"
      and xM: "pp_e_eqv \<sigma> v x (pp_e_closed_den M)"
      unfolding pp_e_closed_logical_stock_def by blast
    have den: "Elem (pp_e_closed_den M) (pp_e_domain \<sigma>)"
      using pp_e_closed_den_in_domain[OF typed] .
    have yM: "pp_e_eqv \<sigma> v y (pp_e_closed_den M)"
      using pp_e_eqv_transitive[OF y x den yx_v xM] .
    show "pp_e_closed_logical_stock \<sigma> v y"
      unfolding pp_e_closed_logical_stock_def
      using y typed logical yM by blast
  next
    assume stock_y: "pp_e_closed_logical_stock \<sigma> v y"
    then obtain M where typed: "[] \<turnstile> M : \<sigma>"
      and logical: "pp_logical_vocabulary M"
      and yM: "pp_e_eqv \<sigma> v y (pp_e_closed_den M)"
      unfolding pp_e_closed_logical_stock_def by blast
    have den: "Elem (pp_e_closed_den M) (pp_e_domain \<sigma>)"
      using pp_e_closed_den_in_domain[OF typed] .
    have xM: "pp_e_eqv \<sigma> v x (pp_e_closed_den M)"
      using pp_e_eqv_transitive[OF x y den xy_v yM] .
    show "pp_e_closed_logical_stock \<sigma> v x"
      unfolding pp_e_closed_logical_stock_def
      using x typed logical xM by blast
  qed
qed

theorem pp_e_closed_logical_stock_application_closed:
  assumes f_stock:
      "pp_e_closed_logical_stock (\<sigma> \<rightarrow>\<^sub>o \<tau>) w f"
    and x_stock: "pp_e_closed_logical_stock \<sigma> w x"
  shows "pp_e_closed_logical_stock \<tau> w (f \<acute> x)"
proof -
  obtain M where M_type: "[] \<turnstile> M : (\<sigma> \<rightarrow>\<^sub>o \<tau>)"
    and M_logical: "pp_logical_vocabulary M"
    and fM:
      "pp_e_eqv (\<sigma> \<rightarrow>\<^sub>o \<tau>) w f
        (pp_e_closed_den M)"
    using f_stock unfolding pp_e_closed_logical_stock_def by blast
  obtain N where N_type: "[] \<turnstile> N : \<sigma>"
    and N_logical: "pp_logical_vocabulary N"
    and xN: "pp_e_eqv \<sigma> w x (pp_e_closed_den N)"
    using x_stock unfolding pp_e_closed_logical_stock_def by blast
  have f_domain: "Elem f (pp_e_domain (\<sigma> \<rightarrow>\<^sub>o \<tau>))"
    using f_stock unfolding pp_e_closed_logical_stock_def by blast
  have x_domain: "Elem x (pp_e_domain \<sigma>)"
    using x_stock unfolding pp_e_closed_logical_stock_def by blast
  have M_domain:
      "Elem (pp_e_closed_den M)
        (pp_e_domain (\<sigma> \<rightarrow>\<^sub>o \<tau>))"
    using pp_e_closed_den_in_domain[OF M_type] .
  have N_domain: "Elem (pp_e_closed_den N) (pp_e_domain \<sigma>)"
    using pp_e_closed_den_in_domain[OF N_type] .
  have app_related:
      "pp_e_eqv \<tau> w (f \<acute> x)
        ((pp_e_closed_den M) \<acute> (pp_e_closed_den N))"
    using pp_e_app_respects[OF fM x_domain N_domain xN] .
  have app_type: "[] \<turnstile> App M N : \<tau>"
    using M_type N_type by (rule has_type.App)
  have app_logical: "pp_logical_vocabulary (App M N)"
    using M_logical N_logical
    by (simp add: pp_logical_vocabulary_def)
  have app_den:
      "pp_e_closed_den (App M N) =
        (pp_e_closed_den M) \<acute> (pp_e_closed_den N)"
    by (simp add: pp_e_closed_den_def)
  have app_domain: "Elem (f \<acute> x) (pp_e_domain \<tau>)"
    using pp_e_app_closed[OF f_domain x_domain] .
  show ?thesis
    unfolding pp_e_closed_logical_stock_def
  proof (intro conjI)
    show "Elem (f \<acute> x) (pp_e_domain \<tau>)"
      using app_domain .
    show "\<exists>A.
        [] \<turnstile> A : \<tau> \<and>
        pp_logical_vocabulary A \<and>
        pp_e_eqv \<tau> w (f \<acute> x) (pp_e_closed_den A)"
    proof (rule exI[of _ "App M N"], intro conjI)
      show "[] \<turnstile> App M N : \<tau>"
        using app_type .
      show "pp_logical_vocabulary (App M N)"
        using app_logical .
      show "pp_e_eqv \<tau> w (f \<acute> x) (pp_e_closed_den (App M N))"
        using app_related app_den by simp
    qed
  qed
qed

theorem pp_e_closed_logical_stock_least:
  assumes admissible:
      "\<And>\<sigma>. pp_e_predicate_admissible \<sigma> (Pure \<sigma>)"
    and contains:
      "\<And>\<sigma> M w. [] \<turnstile> M : \<sigma> \<Longrightarrow>
        pp_logical_vocabulary M \<Longrightarrow>
        Pure \<sigma> w (pp_e_closed_den M)"
    and stock: "pp_e_closed_logical_stock \<sigma> w x"
  shows "Pure \<sigma> w x"
proof -
  obtain M where x: "Elem x (pp_e_domain \<sigma>)"
    and typed: "[] \<turnstile> M : \<sigma>"
    and logical: "pp_logical_vocabulary M"
    and xM: "pp_e_eqv \<sigma> w x (pp_e_closed_den M)"
    using stock unfolding pp_e_closed_logical_stock_def by blast
  have den: "Elem (pp_e_closed_den M) (pp_e_domain \<sigma>)"
    using pp_e_closed_den_in_domain[OF typed] .
  have equivalence:
      "Pure \<sigma> w x \<longleftrightarrow>
        Pure \<sigma> w (pp_e_closed_den M)"
    using admissible[of \<sigma>] x den xM
    unfolding pp_e_predicate_admissible_def
    by blast
  show ?thesis
    using equivalence contains[OF typed logical] by blast
qed

lemma pp_e_closed_logical_stock_contains_eval:
  assumes typed: "[] \<turnstile> M : \<sigma>"
    and logical: "pp_logical_vocabulary M"
  shows "pp_e_closed_logical_stock \<sigma> w (pp_e_eval C \<rho> M)"
proof -
  have const_free: "consts_of M = {}"
    using logical unfolding pp_logical_vocabulary_def .
  have change_constants:
      "pp_e_eval C \<rho> M =
        pp_e_eval pp_e_default_constants \<rho> M"
    using pp_e_eval_const_free[OF const_free] .
  have related:
      "pp_e_eqv \<sigma> w
        (pp_e_eval pp_e_default_constants \<rho> M)
        (pp_e_eval pp_e_default_constants pp_e_closed_env M)"
    using DefaultExactBaconConstants.pp_e_eval_respects[
      OF typed pp_e_empty_env_eqv] .
  have domain:
      "Elem (pp_e_eval C \<rho> M) (pp_e_domain \<sigma>)"
    unfolding change_constants
    using DefaultExactBaconConstants.pp_e_eval_type[
      OF typed pp_e_empty_env_typed]
    by (simp add: pp_e_dom_def)
  show ?thesis
    unfolding pp_e_closed_logical_stock_def pp_e_closed_den_def
  proof (intro conjI)
    show "Elem (pp_e_eval C \<rho> M) (pp_e_domain \<sigma>)"
      using domain .
    show "\<exists>N.
        [] \<turnstile> N : \<sigma> \<and>
        pp_logical_vocabulary N \<and>
        pp_e_eqv \<sigma> w (pp_e_eval C \<rho> M)
          (pp_e_eval pp_e_default_constants pp_e_closed_env N)"
    proof (rule exI[of _ M], intro conjI)
      show "[] \<turnstile> M : \<sigma>"
        using typed .
      show "pp_logical_vocabulary M"
        using logical .
      show "pp_e_eqv \<sigma> w (pp_e_eval C \<rho> M)
          (pp_e_eval pp_e_default_constants pp_e_closed_env M)"
        using related change_constants by simp
    qed
  qed
qed

interpretation ClosedLogicalExactBacon:
  pp_e_moving_internal_parameters pp_e_closed_logical_stock
  by standard (rule pp_e_closed_logical_stock_admissible)

theorem pp_e_closed_logical_purity_gvalid:
  assumes typed: "[] \<turnstile> M : \<sigma>"
    and logical: "pp_logical_vocabulary M"
  shows "ClosedLogicalExactBacon.MovingExactBaconConstants.ExactBaconHenkin.gvalid \<Gamma>
    (pp_pure \<sigma> M)"
proof (rule
    ClosedLogicalExactBacon.MovingExactBaconConstants.ExactBaconHenkin.gvalidI)
  fix env w
  assume "env_ok (map pp_e_dom \<Gamma>) env"
  have eval_pure:
      "pp_e_holds
        (pp_e_eval
          (pp_e_moving_internal_constants pp_e_closed_logical_stock)
          (pp_e_list_env env) (pp_pure \<sigma> M)) w
      \<longleftrightarrow>
        pp_e_closed_logical_stock \<sigma> w
          (pp_e_eval
            (pp_e_moving_internal_constants pp_e_closed_logical_stock)
            (pp_e_list_env env) M)"
    using ClosedLogicalExactBacon.pp_e_moving_eval_pure_holds[
      OF typed pp_e_empty_env_typed, where w=w] .
  have stock:
      "pp_e_closed_logical_stock \<sigma> w
        (pp_e_eval
          (pp_e_moving_internal_constants pp_e_closed_logical_stock)
          (pp_e_list_env env) M)"
    using pp_e_closed_logical_stock_contains_eval[
      OF typed logical] .
  show "pp_e_holds
      (ClosedLogicalExactBacon.MovingExactBaconConstants.pp_e_den
        (pp_pure \<sigma> M) env) w"
    unfolding ClosedLogicalExactBacon.MovingExactBaconConstants.pp_e_den_def
    using eval_pure stock by blast
qed

lemma pp_e_closed_logical_application_closure_holds_iff:
  "pp_e_holds
      (pp_e_eval
        (pp_e_moving_internal_constants pp_e_closed_logical_stock)
        \<rho> (pp_application_closure \<sigma> \<tau>)) w
    \<longleftrightarrow>
    (\<forall>f. Elem f (pp_e_domain (\<sigma> \<rightarrow>\<^sub>o \<tau>)) \<longrightarrow>
      (\<forall>x. Elem x (pp_e_domain \<sigma>) \<longrightarrow>
        pp_e_closed_logical_stock (\<sigma> \<rightarrow>\<^sub>o \<tau>) w f \<and>
        pp_e_closed_logical_stock \<sigma> w x \<longrightarrow>
        pp_e_closed_logical_stock \<tau> w (f \<acute> x)))"
  by (simp add: pp_application_closure_def pp_pure_def
      pp_e_classifier_holds pp_e_app_closed extend_env.simps)

theorem pp_e_closed_logical_application_closure_gvalid:
  "ClosedLogicalExactBacon.MovingExactBaconConstants.ExactBaconHenkin.gvalid \<Gamma>
    (pp_application_closure \<sigma> \<tau>)"
proof (rule
    ClosedLogicalExactBacon.MovingExactBaconConstants.ExactBaconHenkin.gvalidI)
  fix env w
  assume "env_ok (map pp_e_dom \<Gamma>) env"
  show "pp_e_holds
      (ClosedLogicalExactBacon.MovingExactBaconConstants.pp_e_den
        (pp_application_closure \<sigma> \<tau>) env) w"
    unfolding ClosedLogicalExactBacon.MovingExactBaconConstants.pp_e_den_def
      pp_e_closed_logical_application_closure_holds_iff
    using pp_e_closed_logical_stock_application_closed by blast
qed

end
