theory Bacon_Source_Named_H
  imports Bacon_Source_Named_Propositional Bacon_Source_Named_Conversion_Steps
begin

section \<open>Figure 2 directly on named formulas\<close>

text \<open>
  H is generated by PC, UI, EG, Ref, LL, β, η, MP, Gen and Inst.
  Source: Bacon–Dorr Figure 2, p.8, with the context convention on p.7.
  This relation is defined on named terms, not by their encodings or
  semantic validity. The variable stock G is fixed throughout each proof.

  UI and EG apply arbitrary typed predicates. Only literal β substitution
  carries a free-for condition; η carries its usual freshness condition.
  The compatible-step relation permits replacement inside a formula's
  application and abstraction contexts, including binding contexts.
  Implication and biconditional are the literal closed λ-defined operators.

  Language guards enforce well-formedness, not additional principles.
  Source correspondence uses rich G. There is no α or Existence constructor;
  these must be derived. Declaration and language invariance are not yet
  proof correspondence, soundness, or completeness.
\<close>

inductive paper_named_H :: "'c ssignature \<Rightarrow> sgcontext \<Rightarrow> 'c paper_named_term \<Rightarrow> bool"
  for \<Sigma> :: "'c ssignature" and G :: sgcontext where
  PC: "named_PC \<Sigma> G A \<Longrightarrow> paper_named_H \<Sigma> G A"
| UI: "named_in_language paper_logical_type \<Sigma> G
    (named_paper_imp G (named_paper_all \<sigma> F) (NApp F A)) Prop \<Longrightarrow>
    paper_named_H \<Sigma> G (named_paper_imp G (named_paper_all \<sigma> F) (NApp F A))"
| EG: "named_in_language paper_logical_type \<Sigma> G
    (named_paper_imp G (NApp F A) (named_paper_ex \<sigma> F)) Prop \<Longrightarrow>
    paper_named_H \<Sigma> G (named_paper_imp G (NApp F A) (named_paper_ex \<sigma> F))"
| Ref: "named_in_language paper_logical_type \<Sigma> G (named_paper_eq \<sigma> A A) Prop \<Longrightarrow>
    paper_named_H \<Sigma> G (named_paper_eq \<sigma> A A)"
| LL: "named_in_language paper_logical_type \<Sigma> G
    (named_paper_imp G (named_paper_eq \<sigma> A B) (named_paper_imp G (NApp F A) (NApp F B))) Prop \<Longrightarrow>
    paper_named_H \<Sigma> G (named_paper_imp G (named_paper_eq \<sigma> A B)
      (named_paper_imp G (NApp F A) (NApp F B)))"
| Beta: "named_in_language paper_logical_type \<Sigma> G A Prop \<Longrightarrow>
    named_in_language paper_logical_type \<Sigma> G B Prop \<Longrightarrow>
    named_compatible_step named_beta_contract A B \<Longrightarrow>
    named_in_language paper_logical_type \<Sigma> G (named_paper_iff G A B) Prop \<Longrightarrow>
    paper_named_H \<Sigma> G (named_paper_iff G A B)"
| Eta: "named_in_language paper_logical_type \<Sigma> G A Prop \<Longrightarrow>
    named_in_language paper_logical_type \<Sigma> G B Prop \<Longrightarrow>
    named_compatible_step named_eta_contract A B \<Longrightarrow>
    named_in_language paper_logical_type \<Sigma> G (named_paper_iff G A B) Prop \<Longrightarrow>
    paper_named_H \<Sigma> G (named_paper_iff G A B)"
| MP: "paper_named_H \<Sigma> G A \<Longrightarrow> paper_named_H \<Sigma> G (named_paper_imp G A B) \<Longrightarrow>
    named_in_language paper_logical_type \<Sigma> G B Prop \<Longrightarrow> paper_named_H \<Sigma> G B"
| Gen: "paper_named_H \<Sigma> G (named_paper_imp G P Q) \<Longrightarrow> G n = \<sigma> \<Longrightarrow>
    n \<notin> named_fv P \<Longrightarrow> named_in_language paper_logical_type \<Sigma> G
      (named_paper_imp G P (named_paper_all \<sigma> (NLam n Q))) Prop \<Longrightarrow>
    paper_named_H \<Sigma> G (named_paper_imp G P (named_paper_all \<sigma> (NLam n Q)))"
| Inst: "paper_named_H \<Sigma> G (named_paper_imp G P Q) \<Longrightarrow> G n = \<sigma> \<Longrightarrow>
    n \<notin> named_fv Q \<Longrightarrow> named_in_language paper_logical_type \<Sigma> G
      (named_paper_imp G (named_paper_ex \<sigma> (NLam n P)) Q) Prop \<Longrightarrow>
    paper_named_H \<Sigma> G (named_paper_imp G (named_paper_ex \<sigma> (NLam n P)) Q)"

lemma paper_named_H_language:
  assumes derivation: "paper_named_H \<Sigma> G A"
  shows "named_in_language paper_logical_type \<Sigma> G A Prop"
  using derivation by (induction rule: paper_named_H.induct) (auto simp: named_PC_def)

section \<open>Independent local consequence\<close>

text \<open>
  Local consequence has only Assumption, Theorem and MP. An inference
  that generalizes an assumed formula requires its own eigenvariable
  conditions; it is not silently included as an unrestricted local rule.
  Source: the definition of derivability preceding Figure 2, pp.7–8.
\<close>

inductive paper_named_derivable ::
  "'c ssignature \<Rightarrow> sgcontext \<Rightarrow> 'c paper_named_term set \<Rightarrow> 'c paper_named_term \<Rightarrow> bool"
  for \<Sigma> :: "'c ssignature" and G :: sgcontext where
  Assumption: "A \<in> S \<Longrightarrow> named_in_language paper_logical_type \<Sigma> G A Prop \<Longrightarrow>
    paper_named_derivable \<Sigma> G S A"
| Theorem: "paper_named_H \<Sigma> G A \<Longrightarrow> paper_named_derivable \<Sigma> G S A"
| MP: "paper_named_derivable \<Sigma> G S A \<Longrightarrow>
    paper_named_derivable \<Sigma> G S (named_paper_imp G A B) \<Longrightarrow>
    named_in_language paper_logical_type \<Sigma> G B Prop \<Longrightarrow>
    paper_named_derivable \<Sigma> G S B"

lemma paper_named_derivable_language:
  assumes derivation: "paper_named_derivable \<Sigma> G S A"
  shows "named_in_language paper_logical_type \<Sigma> G A Prop"
  using derivation by (induction rule: paper_named_derivable.induct)
    (auto intro: paper_named_H_language)

end
