theory Bacon_Source_Named_Conversion
  imports Bacon_Source_Named_Conversion_Steps Bacon_Source_Prefix_Preservation
begin

section \<open>Named βη chains within the declared language\<close>

text \<open>
  A ≡βη B is generated by contextual, capture-free β and fresh-variable
  η steps, together with reflexivity, symmetry, and transitivity.
  Source: Bacon–Dorr Figure 2, p.8, and Definition 3.1(ii.d), p.44.
  Every node below is typed in the fixed stock G and belongs to ℒ(Σ).

  This relation does not add α as a separate constructor. The connection
  between the independently generated α relation and these βη chains is
  a separate theorem obligation. Nor does the definition stipulate equality
  of de Bruijn representations or semantic denotations.
\<close>

inductive named_beta_eta_in_language ::
  "('l \<Rightarrow> otype) \<Rightarrow> 'c ssignature \<Rightarrow> sgcontext \<Rightarrow> otype \<Rightarrow>
    ('c,'l) named_term \<Rightarrow> ('c,'l) named_term \<Rightarrow> bool"
  for L :: "'l \<Rightarrow> otype" and \<Sigma> :: "'c ssignature" and G :: sgcontext where
  Refl: "named_in_language L \<Sigma> G A \<tau> \<Longrightarrow> named_beta_eta_in_language L \<Sigma> G \<tau> A A"
| Beta: "named_in_language L \<Sigma> G A \<tau> \<Longrightarrow> named_in_language L \<Sigma> G B \<tau> \<Longrightarrow>
    named_compatible_step named_beta_contract A B \<Longrightarrow> named_beta_eta_in_language L \<Sigma> G \<tau> A B"
| Eta: "named_in_language L \<Sigma> G A \<tau> \<Longrightarrow> named_in_language L \<Sigma> G B \<tau> \<Longrightarrow>
    named_compatible_step named_eta_contract A B \<Longrightarrow> named_beta_eta_in_language L \<Sigma> G \<tau> A B"
| Sym: "named_beta_eta_in_language L \<Sigma> G \<tau> A B \<Longrightarrow> named_beta_eta_in_language L \<Sigma> G \<tau> B A"
| Trans: "named_beta_eta_in_language L \<Sigma> G \<tau> A B \<Longrightarrow>
    named_beta_eta_in_language L \<Sigma> G \<tau> B C \<Longrightarrow> named_beta_eta_in_language L \<Sigma> G \<tau> A C"

lemma named_beta_eta_languages:
  assumes conversion: "named_beta_eta_in_language L \<Sigma> G \<tau> A B"
  shows "named_in_language L \<Sigma> G A \<tau> \<and> named_in_language L \<Sigma> G B \<tau>"
  using conversion by (induction rule: named_beta_eta_in_language.induct) blast+

lemma named_encoding_global_language:
  assumes language: "named_in_language L \<Sigma> G A \<tau>"
  shows "sgterm_in_language L \<Sigma> G (named_to_source G [] A) \<tau>"
  using named_to_source_global_language[where ns="[]", OF language]
  by (simp only: named_stack_stock.simps)

lemma named_pair_prefix_languages:
  assumes A: "named_in_language L \<Sigma> G A \<tau>" and B: "named_in_language L \<Sigma> G B \<tau>"
  shows "\<exists>N. \<forall>m\<ge>N.
    sterm_in_language L \<Sigma> (source_prefix G m) (named_to_source G [] A) \<tau> \<and>
    sterm_in_language L \<Sigma> (source_prefix G m) (named_to_source G [] B) \<tau>"
proof -
  let ?N = "max (source_free_bound (named_to_source G [] A)) (source_free_bound (named_to_source G [] B))"
  show ?thesis
  proof (rule exI[where x="?N"], intro allI impI)
    fix m
    assume bound: "?N \<le> m"
    have a_bound: "source_free_bound (named_to_source G [] A) \<le> m" using bound by simp
    have b_bound: "source_free_bound (named_to_source G [] B) \<le> m" using bound by simp
    show "sterm_in_language L \<Sigma> (source_prefix G m) (named_to_source G [] A) \<tau> \<and>
      sterm_in_language L \<Sigma> (source_prefix G m) (named_to_source G [] B) \<tau>"
      by (rule conjI[OF source_language_in_prefix[OF named_encoding_global_language[OF A] a_bound]
        source_language_in_prefix[OF named_encoding_global_language[OF B] b_bound]])
  qed
qed

section \<open>A whole named conversion has sufficiently large common proof frames\<close>

text \<open>
  For a named conversion A ≡βη B, there is a bound N such that every
  prefix of G of length m ≥ N supports its translated, signature-guarded
  source conversion. Transitivity takes the maximum of the bounds for its
  two subderivations. Intermediate terms may need more variables than the
  endpoints; the bound follows the conversion proof, not just its conclusion.
\<close>

theorem named_conversion_prefix_eventual:
  assumes conversion: "named_beta_eta_in_language L \<Sigma> G \<tau> A B"
  shows "\<exists>N. \<forall>m\<ge>N. sbeta_eta_equiv_in_signature L \<Sigma> (source_prefix G m) \<tau>
    (named_to_source G [] A) (named_to_source G [] B)"
  using conversion
proof (induction rule: named_beta_eta_in_language.induct)
  case (Refl A \<tau>)
  obtain N where frames: "\<forall>m\<ge>N.
      sterm_in_language L \<Sigma> (source_prefix G m) (named_to_source G [] A) \<tau> \<and>
      sterm_in_language L \<Sigma> (source_prefix G m) (named_to_source G [] A) \<tau>"
    using named_pair_prefix_languages[OF Refl.hyps Refl.hyps] by (elim exE)
  show ?case
  proof (rule exI[where x=N], intro allI impI)
    fix m
    assume bound: "N \<le> m"
    have language: "sterm_in_language L \<Sigma> (source_prefix G m) (named_to_source G [] A) \<tau>"
      using frames bound by blast
    show "sbeta_eta_equiv_in_signature L \<Sigma> (source_prefix G m) \<tau>
      (named_to_source G [] A) (named_to_source G [] A)"
      using language unfolding sterm_in_language_def by (blast intro: sbeta_eta_equiv_in_signature.Refl)
  qed
next
  case (Beta A \<tau> B)
  obtain N where frames: "\<forall>m\<ge>N.
      sterm_in_language L \<Sigma> (source_prefix G m) (named_to_source G [] A) \<tau> \<and>
      sterm_in_language L \<Sigma> (source_prefix G m) (named_to_source G [] B) \<tau>"
    using named_pair_prefix_languages[OF Beta.hyps(1,2)] by (elim exE)
  have step: "scompatible_step sbeta_contract (named_to_source G [] A) (named_to_source G [] B)"
    by (rule named_beta_step_encoding[OF Beta.hyps(3)])
  show ?case
  proof (rule exI[where x=N], intro allI impI)
    fix m
    assume bound: "N \<le> m"
    have languages: "sterm_in_language L \<Sigma> (source_prefix G m) (named_to_source G [] A) \<tau> \<and>
      sterm_in_language L \<Sigma> (source_prefix G m) (named_to_source G [] B) \<tau>"
      using frames bound by blast
    show "sbeta_eta_equiv_in_signature L \<Sigma> (source_prefix G m) \<tau>
      (named_to_source G [] A) (named_to_source G [] B)"
      using languages step unfolding sterm_in_language_def
      by (blast intro: sbeta_eta_equiv_in_signature.Beta)
  qed
next
  case (Eta A \<tau> B)
  obtain N where frames: "\<forall>m\<ge>N.
      sterm_in_language L \<Sigma> (source_prefix G m) (named_to_source G [] A) \<tau> \<and>
      sterm_in_language L \<Sigma> (source_prefix G m) (named_to_source G [] B) \<tau>"
    using named_pair_prefix_languages[OF Eta.hyps(1,2)] by (elim exE)
  have step: "scompatible_step seta_contract (named_to_source G [] A) (named_to_source G [] B)"
    by (rule named_eta_step_encoding[OF Eta.hyps(3)])
  show ?case
  proof (rule exI[where x=N], intro allI impI)
    fix m
    assume bound: "N \<le> m"
    have languages: "sterm_in_language L \<Sigma> (source_prefix G m) (named_to_source G [] A) \<tau> \<and>
      sterm_in_language L \<Sigma> (source_prefix G m) (named_to_source G [] B) \<tau>"
      using frames bound by blast
    show "sbeta_eta_equiv_in_signature L \<Sigma> (source_prefix G m) \<tau>
      (named_to_source G [] A) (named_to_source G [] B)"
      using languages step unfolding sterm_in_language_def
      by (blast intro: sbeta_eta_equiv_in_signature.Eta)
  qed
next
  case (Sym \<tau> A B)
  obtain N where frames: "\<forall>m\<ge>N. sbeta_eta_equiv_in_signature L \<Sigma> (source_prefix G m) \<tau>
    (named_to_source G [] A) (named_to_source G [] B)" using Sym.IH by (elim exE)
  show ?case
  proof (rule exI[where x=N], intro allI impI)
    fix m
    assume bound: "N \<le> m"
    have original: "sbeta_eta_equiv_in_signature L \<Sigma> (source_prefix G m) \<tau>
      (named_to_source G [] A) (named_to_source G [] B)" using frames bound by blast
    show "sbeta_eta_equiv_in_signature L \<Sigma> (source_prefix G m) \<tau>
      (named_to_source G [] B) (named_to_source G [] A)"
      by (rule sbeta_eta_equiv_in_signature.Sym[OF original])
  qed
next
  case (Trans \<tau> A B C)
  obtain N where first: "\<forall>m\<ge>N. sbeta_eta_equiv_in_signature L \<Sigma> (source_prefix G m) \<tau>
    (named_to_source G [] A) (named_to_source G [] B)" using Trans.IH(1) by (elim exE)
  obtain K where second: "\<forall>m\<ge>K. sbeta_eta_equiv_in_signature L \<Sigma> (source_prefix G m) \<tau>
    (named_to_source G [] B) (named_to_source G [] C)" using Trans.IH(2) by (elim exE)
  show ?case
  proof (rule exI[where x="max N K"], intro allI impI)
    fix m
    assume bound: "max N K \<le> m"
    have left: "sbeta_eta_equiv_in_signature L \<Sigma> (source_prefix G m) \<tau>
      (named_to_source G [] A) (named_to_source G [] B)" using first bound by auto
    have right: "sbeta_eta_equiv_in_signature L \<Sigma> (source_prefix G m) \<tau>
      (named_to_source G [] B) (named_to_source G [] C)" using second bound by auto
    show "sbeta_eta_equiv_in_signature L \<Sigma> (source_prefix G m) \<tau>
      (named_to_source G [] A) (named_to_source G [] C)"
      by (rule sbeta_eta_equiv_in_signature.Trans[OF left right])
  qed
qed

end
