theory Bacon_Source_Global_H
  imports Bacon_Source_Rich_Stock Bacon_Source_Finite_Typing
    Bacon_Source_Proof_Connectives
begin

section \<open>Figure 2 over a fixed stock of typed variables\<close>

text \<open>
  H is generated by PC, UI, EG, Ref, LL, β, η, MP, Gen, and Inst
  (Bacon–Dorr Figure 2, p. 8). The global type assignment G is fixed
  throughout a proof. Gen and Inst bind a chosen existing variable; they
  do not shrink the set of variables available in later proof steps.

  Isabelle representation: paper_global_H has precisely these ten
  constructors. Every formula is guarded by the source language judgment.
  The guards on inference conclusions merely enforce well-formedness;
  they are not extra logical axioms. Implication and biconditional are the
  literal Figure 1 λ-definitions. UI and EG apply arbitrary predicates,
  including predicates not syntactically displayed as abstractions.

  Source use requires sg_rich G. The relation is also defined for other G
  so structural metatheorems need not carry an unused richness premise.
  No Existence constructor is added: the source derives Existence using
  a variable of the required type. Its derivation and the two-way target
  proof translation are separate obligations. The raw binding convention
  still requires named-variable/α-equivalence correspondence.
\<close>

definition paper_global_PC ::
  "'c ssignature \<Rightarrow> sgcontext \<Rightarrow> 'c paper_term \<Rightarrow> bool" where
  "paper_global_PC \<Sigma> G A \<longleftrightarrow>
    sgterm_in_language paper_logical_type \<Sigma> G A Prop \<and>
    (\<exists>P :: nat sprop_template. \<exists>v. sprop_tautology P \<and> A = paper_prop_instance v P)"

inductive paper_global_H ::
  "'c ssignature \<Rightarrow> sgcontext \<Rightarrow> 'c paper_term \<Rightarrow> bool"
  for \<Sigma> :: "'c ssignature" and G :: sgcontext where
  PC: "paper_global_PC \<Sigma> G A \<Longrightarrow> paper_global_H \<Sigma> G A"
| UI: "sgterm_in_language paper_logical_type \<Sigma> G
    (paper_imp (SApp (SLogical (SAll \<sigma>)) F) (SApp F A)) Prop \<Longrightarrow>
    paper_global_H \<Sigma> G (paper_imp (SApp (SLogical (SAll \<sigma>)) F) (SApp F A))"
| EG: "sgterm_in_language paper_logical_type \<Sigma> G
    (paper_imp (SApp F A) (SApp (SLogical (SEx \<sigma>)) F)) Prop \<Longrightarrow>
    paper_global_H \<Sigma> G (paper_imp (SApp F A) (SApp (SLogical (SEx \<sigma>)) F))"
| Ref: "sgterm_in_language paper_logical_type \<Sigma> G
    (SApp (SApp (SLogical (SEq \<sigma>)) A) A) Prop \<Longrightarrow>
    paper_global_H \<Sigma> G (SApp (SApp (SLogical (SEq \<sigma>)) A) A)"
| LL: "sgterm_in_language paper_logical_type \<Sigma> G
    (paper_imp (SApp (SApp (SLogical (SEq \<sigma>)) A) B)
      (paper_imp (SApp F A) (SApp F B))) Prop \<Longrightarrow>
    paper_global_H \<Sigma> G (paper_imp (SApp (SApp (SLogical (SEq \<sigma>)) A) B)
      (paper_imp (SApp F A) (SApp F B)))"
| Beta: "sgterm_in_language paper_logical_type \<Sigma> G A Prop \<Longrightarrow>
    sgterm_in_language paper_logical_type \<Sigma> G B Prop \<Longrightarrow>
    scompatible_step sbeta_contract A B \<Longrightarrow>
    sgterm_in_language paper_logical_type \<Sigma> G (paper_iff A B) Prop \<Longrightarrow>
    paper_global_H \<Sigma> G (paper_iff A B)"
| Eta: "sgterm_in_language paper_logical_type \<Sigma> G A Prop \<Longrightarrow>
    sgterm_in_language paper_logical_type \<Sigma> G B Prop \<Longrightarrow>
    scompatible_step seta_contract A B \<Longrightarrow>
    sgterm_in_language paper_logical_type \<Sigma> G (paper_iff A B) Prop \<Longrightarrow>
    paper_global_H \<Sigma> G (paper_iff A B)"
| MP: "paper_global_H \<Sigma> G A \<Longrightarrow> paper_global_H \<Sigma> G (paper_imp A B) \<Longrightarrow>
    sgterm_in_language paper_logical_type \<Sigma> G B Prop \<Longrightarrow>
    paper_global_H \<Sigma> G B"
| Gen: "paper_global_H \<Sigma> G (paper_imp P Q) \<Longrightarrow> G n = \<sigma> \<Longrightarrow>
    n \<notin> sfv P \<Longrightarrow> sgterm_in_language paper_logical_type \<Sigma> G
      (paper_imp P (SApp (SLogical (SAll \<sigma>)) (SLam \<sigma> (sclose n Q)))) Prop \<Longrightarrow>
    paper_global_H \<Sigma> G (paper_imp P (SApp (SLogical (SAll \<sigma>)) (SLam \<sigma> (sclose n Q))))"
| Inst: "paper_global_H \<Sigma> G (paper_imp P Q) \<Longrightarrow> G n = \<sigma> \<Longrightarrow>
    n \<notin> sfv Q \<Longrightarrow> sgterm_in_language paper_logical_type \<Sigma> G
      (paper_imp (SApp (SLogical (SEx \<sigma>)) (SLam \<sigma> (sclose n P))) Q) Prop \<Longrightarrow>
    paper_global_H \<Sigma> G (paper_imp (SApp (SLogical (SEx \<sigma>)) (SLam \<sigma> (sclose n P))) Q)"

lemma paper_global_H_language:
  assumes "paper_global_H \<Sigma> G A"
  shows "sgterm_in_language paper_logical_type \<Sigma> G A Prop"
  using assms by (induction rule: paper_global_H.induct)
    (auto simp only: paper_global_PC_def)

subsection \<open>PC has the same finite-support instances\<close>

lemma paper_global_PC_finite_frame:
  assumes pc: "paper_global_PC \<Sigma> G A"
    and agrees: "\<And>n. n \<in> sfv A \<Longrightarrow> lookup \<Gamma> n = Some (G n)"
  shows "paper_PC \<Sigma> \<Gamma> A"
proof -
  have typed: "has_sgtype paper_logical_type G A Prop"
    and sig: "sterm_in_signature \<Sigma> A"
    and template: "\<exists>P :: nat sprop_template. \<exists>v. sprop_tautology P \<and> A = paper_prop_instance v P"
    using pc unfolding paper_global_PC_def sgterm_in_language_def by blast+
  have finite_type: "has_stype paper_logical_type \<Gamma> A Prop"
    by (rule source_global_to_finite_typing[OF typed agrees])
  show ?thesis using finite_type sig template
    by (simp only: paper_PC_def sterm_in_language_def; blast)
qed

theorem paper_global_PC_translation:
  assumes pc: "paper_global_PC \<Sigma> G A"
    and agrees: "\<And>n. n \<in> sfv A \<Longrightarrow> lookup \<Gamma> n = Some (G n)"
  shows "pH_proves \<Sigma> \<Gamma> (paper_to_pterm A)"
  by (rule paper_PC_translation[OF paper_global_PC_finite_frame[OF pc agrees]])

end
