theory Bacon_Parametric_BBK_Semantics
  imports Bacon_Parametric_Beta
begin

section \<open>BBK models for arbitrary-name languages\<close>

text \<open>
  A BBK model M has domains Dσ, interpretation ⟦A⟧ᴹᵍ, and valuation V.
  M,g ⊨ A means V(⟦A⟧ᴹᵍ); M,g ⊨ A =σ B iff ⟦A⟧ᴹᵍ = ⟦B⟧ᴹᵍ.

  Isabelle representation: pbbk_model fixes an arbitrary 'c psignature and
  whole-term denote/valuation functions on an independent carrier 'v.
  Neither carrier is assumed countable.  denote_rename explicitly requires
  coherence under type-respecting injective renaming of free de Bruijn slots.

  Status: the earlier BBK interface ported to pterm (Bacon–Dorr Definition
  3.1), not a constructed model or completeness proof.  No Functionality,
  injective propositional valuation, or full function spaces are assumed.
  Actual equality, full F types, and dedicated logical constructors remain;
  the book’s broader Leibniz-equivalence semantics is distinct.
\<close>

subsection \<open>Typed beta-eta equivalence\<close>

text \<open>
  A ≡βη B is typed conversion generated by contextual β and η steps,
  symmetry, and transitivity.

  Isabelle representation: pbeta_eta_equiv records the common type σ and context
  Γ; pbeta_eta_equiv_types recovers the typing of both endpoints.

  Status: conversion is a syntactic relation here, not object-language
  theoremhood or a quotient construction.
\<close>

inductive pbeta_eta_equiv ::
    "ctx \<Rightarrow> otype \<Rightarrow> 'c pterm \<Rightarrow> 'c pterm \<Rightarrow> bool" where
  Refl: "has_ptype \<Gamma> M \<tau> \<Longrightarrow> pbeta_eta_equiv \<Gamma> \<tau> M M"
| Beta: "has_ptype \<Gamma> M \<tau> \<Longrightarrow> has_ptype \<Gamma> N \<tau> \<Longrightarrow>
    pcompatible_step pbeta_contract M N \<Longrightarrow> pbeta_eta_equiv \<Gamma> \<tau> M N"
| Eta: "has_ptype \<Gamma> M \<tau> \<Longrightarrow> has_ptype \<Gamma> N \<tau> \<Longrightarrow>
    pcompatible_step peta_contract M N \<Longrightarrow> pbeta_eta_equiv \<Gamma> \<tau> M N"
| Sym: "pbeta_eta_equiv \<Gamma> \<tau> M N \<Longrightarrow> pbeta_eta_equiv \<Gamma> \<tau> N M"
| Trans: "pbeta_eta_equiv \<Gamma> \<tau> M N \<Longrightarrow> pbeta_eta_equiv \<Gamma> \<tau> N P \<Longrightarrow>
    pbeta_eta_equiv \<Gamma> \<tau> M P"

lemma pbeta_eta_equiv_types:
  assumes "pbeta_eta_equiv \<Gamma> \<tau> M N"
  shows "has_ptype \<Gamma> M \<tau> \<and> has_ptype \<Gamma> N \<tau>"
  using assms
proof (induction rule: pbeta_eta_equiv.induct)
  case (Refl \<Gamma> M \<tau>)
  show ?case by (rule conjI[OF Refl.hyps Refl.hyps])
next
  case (Beta \<Gamma> M \<tau> N)
  show ?case by (rule conjI[OF Beta.hyps(1,2)])
next
  case (Eta \<Gamma> M \<tau> N)
  show ?case by (rule conjI[OF Eta.hyps(1,2)])
next
  case (Sym \<Gamma> \<tau> M N)
  show ?case by (rule conjI[OF conjunct2[OF Sym.IH] conjunct1[OF Sym.IH]])
next
  case (Trans \<Gamma> \<tau> M N P)
  show ?case by (rule conjI[OF conjunct1[OF Trans.IH(1)] conjunct2[OF Trans.IH(2)]])
qed

text \<open>
  In Definition 3.1(ii.d), Bacon and Dorr quantify over βη-equivalent
  terms of ℒ(Σ).  We represent this as the closure of the immediate
  conversions within that declared language. A raw β-expansion can introduce
  a foreign constant and later erase it. This distinguishes permitted paths,
  not necessarily equivalence of endpoints already in ℒ(Σ). The theorem
  pbeta_eta_equiv_in_signature_raw below proves guarded-to-raw conversion;
  the converse for typed Σ-endpoints remains a source-correspondence
  obligation. A suitable Church–Rosser argument could establish it.
  BBK models below use the explicit language-relative relation.
\<close>

inductive pbeta_eta_equiv_in_signature ::
    "'c psignature \<Rightarrow> ctx \<Rightarrow> otype \<Rightarrow> 'c pterm \<Rightarrow> 'c pterm \<Rightarrow> bool"
  for \<Sigma> :: "'c psignature" where
  Refl: "has_ptype \<Gamma> M \<tau> \<Longrightarrow> pterm_in_signature \<Sigma> M \<Longrightarrow>
    pbeta_eta_equiv_in_signature \<Sigma> \<Gamma> \<tau> M M"
| Beta: "has_ptype \<Gamma> M \<tau> \<Longrightarrow> has_ptype \<Gamma> N \<tau> \<Longrightarrow>
    pterm_in_signature \<Sigma> M \<Longrightarrow> pterm_in_signature \<Sigma> N \<Longrightarrow>
    pcompatible_step pbeta_contract M N \<Longrightarrow>
    pbeta_eta_equiv_in_signature \<Sigma> \<Gamma> \<tau> M N"
| Eta: "has_ptype \<Gamma> M \<tau> \<Longrightarrow> has_ptype \<Gamma> N \<tau> \<Longrightarrow>
    pterm_in_signature \<Sigma> M \<Longrightarrow> pterm_in_signature \<Sigma> N \<Longrightarrow>
    pcompatible_step peta_contract M N \<Longrightarrow>
    pbeta_eta_equiv_in_signature \<Sigma> \<Gamma> \<tau> M N"
| Sym: "pbeta_eta_equiv_in_signature \<Sigma> \<Gamma> \<tau> M N \<Longrightarrow>
    pbeta_eta_equiv_in_signature \<Sigma> \<Gamma> \<tau> N M"
| Trans: "pbeta_eta_equiv_in_signature \<Sigma> \<Gamma> \<tau> M N \<Longrightarrow>
    pbeta_eta_equiv_in_signature \<Sigma> \<Gamma> \<tau> N P \<Longrightarrow>
    pbeta_eta_equiv_in_signature \<Sigma> \<Gamma> \<tau> M P"

lemma pbeta_eta_equiv_in_signature_data:
  assumes "pbeta_eta_equiv_in_signature \<Sigma> \<Gamma> \<tau> M N"
  shows "has_ptype \<Gamma> M \<tau> \<and> has_ptype \<Gamma> N \<tau> \<and>
    pterm_in_signature \<Sigma> M \<and> pterm_in_signature \<Sigma> N"
  using assms by (induction rule: pbeta_eta_equiv_in_signature.induct) blast+

lemma pbeta_eta_equiv_in_signature_raw:
  "pbeta_eta_equiv_in_signature \<Sigma> \<Gamma> \<tau> M N \<Longrightarrow>
    pbeta_eta_equiv \<Gamma> \<tau> M N"
  by (induction rule: pbeta_eta_equiv_in_signature.induct)
    (auto intro: pbeta_eta_equiv.intros)

subsection \<open>Free slots and typed environments\<close>

text \<open>
  The assignment g gives each free v:σ a value in Dσ; g[v ↦ a] extends
  the assignment beneath a binder.

  Isabelle representation: pbbk_fv tracks de Bruijn slots, pbbk_env_typed checks
  the finite context, and pbbk_extend inserts slot zero.  Off-context values
  of the total HOL assignment are unconstrained.

  Status: environment and signature lemmas for arbitrary carriers; no model
  existence follows from these definitions.
\<close>

fun pbbk_fv :: "'c pterm \<Rightarrow> nat set" where
  "pbbk_fv (PVar n) = {n}"
| "pbbk_fv (PConst c \<sigma>) = {}"
| "pbbk_fv (PApp M N) = pbbk_fv M \<union> pbbk_fv N"
| "pbbk_fv (PLam \<sigma> M) = {n. Suc n \<in> pbbk_fv M}"
| "pbbk_fv (PEq \<sigma> M N) = pbbk_fv M \<union> pbbk_fv N"
| "pbbk_fv (PNeg A) = pbbk_fv A"
| "pbbk_fv (PConj A B) = pbbk_fv A \<union> pbbk_fv B"
| "pbbk_fv (PDisj A B) = pbbk_fv A \<union> pbbk_fv B"
| "pbbk_fv (PImp A B) = pbbk_fv A \<union> pbbk_fv B"
| "pbbk_fv (PForall \<sigma> A) = {n. Suc n \<in> pbbk_fv A}"
| "pbbk_fv (PExists \<sigma> A) = {n. Suc n \<in> pbbk_fv A}"

definition pbbk_env_typed ::
    "(otype \<Rightarrow> 'v set) \<Rightarrow> ctx \<Rightarrow> (nat \<Rightarrow> 'v) \<Rightarrow> bool" where
  "pbbk_env_typed D \<Gamma> g \<longleftrightarrow>
    (\<forall>n \<sigma>. lookup \<Gamma> n = Some \<sigma> \<longrightarrow> g n \<in> D \<sigma>)"

definition pbbk_extend :: "'v \<Rightarrow> (nat \<Rightarrow> 'v) \<Rightarrow> nat \<Rightarrow> 'v" where
  "pbbk_extend a g = case_nat a g"

lemma pbbk_extend_zero[simp]: "pbbk_extend a g 0 = a"
  by (simp add: pbbk_extend_def)

lemma pbbk_extend_Suc[simp]: "pbbk_extend a g (Suc n) = g n"
  by (simp add: pbbk_extend_def)

lemma pbbk_env_empty:
  "pbbk_env_typed D [] g"
  by (simp add: pbbk_env_typed_def lookup_def)

lemma pbbk_env_lookup:
  assumes env: "pbbk_env_typed D \<Gamma> g" and index: "lookup \<Gamma> n = Some \<sigma>"
  shows "g n \<in> D \<sigma>"
proof -
  have all: "\<forall>n \<sigma>. lookup \<Gamma> n = Some \<sigma> \<longrightarrow> g n \<in> D \<sigma>"
    using env by (simp only: pbbk_env_typed_def)
  have at_n: "\<forall>\<sigma>. lookup \<Gamma> n = Some \<sigma> \<longrightarrow> g n \<in> D \<sigma>"
    by (rule spec[OF all])
  have at_type: "lookup \<Gamma> n = Some \<sigma> \<longrightarrow> g n \<in> D \<sigma>"
    by (rule spec[OF at_n])
  show ?thesis by (rule mp[OF at_type index])
qed

lemma pbbk_env_extend:
  assumes env: "pbbk_env_typed D \<Gamma> g" and domain: "a \<in> D \<sigma>"
  shows "pbbk_env_typed D (\<sigma> # \<Gamma>) (pbbk_extend a g)"
proof (unfold pbbk_env_typed_def, intro allI impI)
  fix n \<tau>
  assume index: "lookup (\<sigma> # \<Gamma>) n = Some \<tau>"
  show "pbbk_extend a g n \<in> D \<tau>"
  proof (cases n)
    case 0
    have eq: "\<tau> = \<sigma>" using index by (simp add: 0)
    show ?thesis using domain by (simp only: 0 eq pbbk_extend_zero)
  next
    case (Suc m)
    have index': "lookup \<Gamma> m = Some \<tau>" using index by (simp add: Suc)
    have old: "g m \<in> D \<tau>" by (rule pbbk_env_lookup[OF env index'])
    show ?thesis by (simp only: Suc pbbk_extend_Suc old)
  qed
qed

lemma pbbk_env_tail:
  assumes env: "pbbk_env_typed D (\<sigma> # \<Gamma>) g"
  shows "pbbk_env_typed D \<Gamma> (\<lambda>n. g (Suc n))"
proof (unfold pbbk_env_typed_def, intro allI impI)
  fix n \<tau>
  assume index: "lookup \<Gamma> n = Some \<tau>"
  have lifted: "lookup (\<sigma> # \<Gamma>) (Suc n) = Some \<tau>" using index by simp
  show "g (Suc n) \<in> D \<tau>" by (rule pbbk_env_lookup[OF env lifted])
qed

lemma pbbk_signature_subst0:
  assumes body: "pterm_in_signature \<Sigma> A" and arg: "pterm_in_signature \<Sigma> T"
  shows "pterm_in_signature \<Sigma> (psubst0 T A)"
  unfolding psubst0_def
  by (rule psubst_signature[OF body]) (case_tac n; simp add: arg)

subsection \<open>The exact model interface\<close>

text \<open>
  ⟦A⟧ᴹᵍ ∈ Dσ for A:σ in ℒ(Σ), and M,g ⊨ A =σ B exactly when
  ⟦A⟧ᴹᵍ = ⟦B⟧ᴹᵍ.  Quantifiers range over the displayed Dσ.

  Isabelle representation: pbbk_model lists all typing, application, locality,
  injective-renaming, βη, and truth clauses.  pbbk_satisfies and
  pbbk_valid_in_context distinguish truth at g from validity at all typed g.

  Status: an explicit conditional BBK interface, not Functionality, a
  truth-value collapse, or a constructed model.
\<close>

locale pbbk_model =
  fixes signature :: "'c psignature"
    and domain :: "otype \<Rightarrow> 'v set"
    and denote :: "(nat \<Rightarrow> 'v) \<Rightarrow> 'c pterm \<Rightarrow> 'v"
    and valuation :: "'v \<Rightarrow> bool"
  assumes domain_nonempty: "domain \<sigma> \<noteq> {}"
    and denote_type:
      "has_ptype \<Gamma> M \<sigma> \<Longrightarrow> pterm_in_signature signature M \<Longrightarrow>
       pbbk_env_typed domain \<Gamma> g \<Longrightarrow> denote g M \<in> domain \<sigma>"
    and denote_var:
      "lookup \<Gamma> n = Some \<sigma> \<Longrightarrow> pbbk_env_typed domain \<Gamma> g \<Longrightarrow>
       denote g (PVar n) = g n"
    and denote_application_cong:
      "has_ptype \<Gamma> F (\<sigma> \<rightarrow>\<^sub>o \<tau>) \<Longrightarrow> has_ptype \<Gamma> A \<sigma> \<Longrightarrow>
       has_ptype \<Delta> G (\<sigma> \<rightarrow>\<^sub>o \<tau>) \<Longrightarrow> has_ptype \<Delta> B \<sigma> \<Longrightarrow>
       pterm_in_signature signature (PApp F A) \<Longrightarrow>
       pterm_in_signature signature (PApp G B) \<Longrightarrow>
       pbbk_env_typed domain \<Gamma> g \<Longrightarrow> pbbk_env_typed domain \<Delta> h \<Longrightarrow>
       denote g F = denote h G \<Longrightarrow> denote g A = denote h B \<Longrightarrow>
       denote g (PApp F A) = denote h (PApp G B)"
    and denote_locality:
      "has_ptype \<Gamma> M \<sigma> \<Longrightarrow> has_ptype \<Delta> M \<sigma> \<Longrightarrow>
       pterm_in_signature signature M \<Longrightarrow>
       pbbk_env_typed domain \<Gamma> g \<Longrightarrow> pbbk_env_typed domain \<Delta> h \<Longrightarrow>
       (\<And>n. n \<in> pbbk_fv M \<Longrightarrow> g n = h n) \<Longrightarrow> denote g M = denote h M"
    and denote_rename:
      "has_ptype \<Gamma> M \<sigma> \<Longrightarrow> pterm_in_signature signature M \<Longrightarrow>
       inj r \<Longrightarrow> pbbk_env_typed domain \<Delta> g \<Longrightarrow>
       (\<And>n \<tau>. lookup \<Gamma> n = Some \<tau> \<Longrightarrow> lookup \<Delta> (r n) = Some \<tau>) \<Longrightarrow>
       denote g (prename r M) = denote (\<lambda>n. g (r n)) M"
    and denote_beta_eta:
      "pbeta_eta_equiv_in_signature signature \<Gamma> \<sigma> M N \<Longrightarrow>
       pterm_in_signature signature M \<Longrightarrow> pterm_in_signature signature N \<Longrightarrow>
       pbbk_env_typed domain \<Gamma> g \<Longrightarrow> denote g M = denote g N"
    and valuation_neg:
      "has_ptype \<Gamma> A Prop \<Longrightarrow> pterm_in_signature signature A \<Longrightarrow>
       pbbk_env_typed domain \<Gamma> g \<Longrightarrow>
       valuation (denote g (PNeg A)) = (\<not> valuation (denote g A))"
    and valuation_conj:
      "has_ptype \<Gamma> A Prop \<Longrightarrow> has_ptype \<Gamma> B Prop \<Longrightarrow>
       pterm_in_signature signature A \<Longrightarrow> pterm_in_signature signature B \<Longrightarrow>
       pbbk_env_typed domain \<Gamma> g \<Longrightarrow>
       valuation (denote g (PConj A B)) = (valuation (denote g A) \<and> valuation (denote g B))"
    and valuation_disj:
      "has_ptype \<Gamma> A Prop \<Longrightarrow> has_ptype \<Gamma> B Prop \<Longrightarrow>
       pterm_in_signature signature A \<Longrightarrow> pterm_in_signature signature B \<Longrightarrow>
       pbbk_env_typed domain \<Gamma> g \<Longrightarrow>
       valuation (denote g (PDisj A B)) = (valuation (denote g A) \<or> valuation (denote g B))"
    and valuation_imp:
      "has_ptype \<Gamma> A Prop \<Longrightarrow> has_ptype \<Gamma> B Prop \<Longrightarrow>
       pterm_in_signature signature A \<Longrightarrow> pterm_in_signature signature B \<Longrightarrow>
       pbbk_env_typed domain \<Gamma> g \<Longrightarrow>
       valuation (denote g (PImp A B)) = (valuation (denote g A) \<longrightarrow> valuation (denote g B))"
    and valuation_forall:
      "has_ptype (\<sigma> # \<Gamma>) A Prop \<Longrightarrow> pterm_in_signature signature A \<Longrightarrow>
       pbbk_env_typed domain \<Gamma> g \<Longrightarrow>
       valuation (denote g (PForall \<sigma> A)) =
         (\<forall>a \<in> domain \<sigma>. valuation (denote (pbbk_extend a g) A))"
    and valuation_exists:
      "has_ptype (\<sigma> # \<Gamma>) A Prop \<Longrightarrow> pterm_in_signature signature A \<Longrightarrow>
       pbbk_env_typed domain \<Gamma> g \<Longrightarrow>
       valuation (denote g (PExists \<sigma> A)) =
         (\<exists>a \<in> domain \<sigma>. valuation (denote (pbbk_extend a g) A))"
    and valuation_identity:
      "has_ptype \<Gamma> M \<sigma> \<Longrightarrow> has_ptype \<Gamma> N \<sigma> \<Longrightarrow>
       pterm_in_signature signature M \<Longrightarrow> pterm_in_signature signature N \<Longrightarrow>
       pbbk_env_typed domain \<Gamma> g \<Longrightarrow>
       valuation (denote g (PEq \<sigma> M N)) = (denote g M = denote g N)"
begin

definition pbbk_satisfies :: "(nat \<Rightarrow> 'v) \<Rightarrow> 'c pterm \<Rightarrow> bool" where
  "pbbk_satisfies g A \<longleftrightarrow> valuation (denote g A)"

definition pbbk_valid_in_context :: "ctx \<Rightarrow> 'c pterm \<Rightarrow> bool" where
  "pbbk_valid_in_context \<Gamma> A \<longleftrightarrow>
    has_ptype \<Gamma> A Prop \<and> pterm_in_signature signature A \<and>
    (\<forall>g. pbbk_env_typed domain \<Gamma> g \<longrightarrow> pbbk_satisfies g A)"

subsection \<open>One binder: renaming coherence and beta substitution\<close>

text \<open>
  ⟦A[B/v]⟧ᴹᵍ = ⟦A⟧ᴹʰ, where h = g[v ↦ ⟦B⟧ᴹᵍ].

  Isabelle representation: pbbk_shift_assignment first removes the fresh-slot
  encoding change; pbbk_denote_beta and pbbk_one_binder combine that fact
  with application coherence and contextual β conversion.

  Status: one-binder semantic substitution for open as well as closed bodies,
  with all typing and signature premises retained.
\<close>

lemma pbbk_shift_assignment:
  assumes typed: "has_ptype \<Gamma> M \<tau>" and sig: "pterm_in_signature signature M"
    and env: "pbbk_env_typed domain \<Gamma> g" and domain_member: "a \<in> domain \<sigma>"
  shows "denote (pbbk_extend a g) (pshift M) = denote g M"
proof -
  have extended: "pbbk_env_typed domain (\<sigma> # \<Gamma>) (pbbk_extend a g)"
    by (rule pbbk_env_extend[OF env domain_member])
  have injection: "inj Suc" by (rule injI) simp
  have ren: "lookup (\<sigma> # \<Gamma>) (Suc n) = Some \<rho>"
    if index: "lookup \<Gamma> n = Some \<rho>" for n \<rho>
    using index by simp
  have original: "denote (pbbk_extend a g) (prename Suc M) =
    denote (\<lambda>n. pbbk_extend a g (Suc n)) M"
    by (rule denote_rename[OF typed sig injection extended ren])
  show ?thesis using original by (simp only: pshift_def pbbk_extend_Suc)
qed

lemma pbbk_denote_beta:
  assumes body: "has_ptype (\<sigma> # \<Gamma>) A \<tau>" and arg: "has_ptype \<Gamma> T \<sigma>"
    and sigA: "pterm_in_signature signature A" and sigT: "pterm_in_signature signature T"
    and env: "pbbk_env_typed domain \<Gamma> g"
  shows "denote g (PApp (PLam \<sigma> A) T) = denote g (psubst0 T A)"
proof -
  have lam: "has_ptype \<Gamma> (PLam \<sigma> A) (\<sigma> \<rightarrow>\<^sub>o \<tau>)"
    by (rule has_ptype.PLam[OF body])
  have app: "has_ptype \<Gamma> (PApp (PLam \<sigma> A) T) \<tau>"
    by (rule has_ptype.PApp[OF lam arg])
  have sub: "has_ptype \<Gamma> (psubst0 T A) \<tau>"
    by (rule psubst0_preserves_typing[OF body arg])
  have step: "pcompatible_step pbeta_contract (PApp (PLam \<sigma> A) T) (psubst0 T A)"
    by (intro pcompatible_step.root pbeta_contract.beta)
  have sigapp: "pterm_in_signature signature (PApp (PLam \<sigma> A) T)"
    using sigA sigT by simp
  have sigsub: "pterm_in_signature signature (psubst0 T A)"
    by (rule pbbk_signature_subst0[OF sigA sigT])
  have conv: "pbeta_eta_equiv_in_signature signature \<Gamma> \<tau>
      (PApp (PLam \<sigma> A) T) (psubst0 T A)"
    by (rule pbeta_eta_equiv_in_signature.Beta[OF app sub sigapp sigsub step])
  show ?thesis by (rule denote_beta_eta[OF conv sigapp sigsub env])
qed

lemma pbbk_beta_slot_restore:
  "psubst0 (PVar 0) (prename (lift_ren Suc) A) = A"
  unfolding psubst0_def
  by (rule psubst_prename_inverse) (case_tac n; simp)

lemma pbbk_one_binder:
  assumes body: "has_ptype (\<sigma> # \<Gamma>) A \<tau>" and arg: "has_ptype \<Gamma> T \<sigma>"
    and sigA: "pterm_in_signature signature A" and sigT: "pterm_in_signature signature T"
    and env: "pbbk_env_typed domain \<Gamma> g"
  shows "denote (pbbk_extend (denote g T) g) A = denote g (psubst0 T A)"
proof -
  let ?h = "pbbk_extend (denote g T) g"
  let ?L = "PLam \<sigma> A"
  have L: "has_ptype \<Gamma> ?L (\<sigma> \<rightarrow>\<^sub>o \<tau>)" by (rule has_ptype.PLam[OF body])
  have sigL: "pterm_in_signature signature ?L" using sigA by simp
  have Tden: "denote g T \<in> domain \<sigma>" by (rule denote_type[OF arg sigT env])
  have extended: "pbbk_env_typed domain (\<sigma> # \<Gamma>) ?h"
    by (rule pbbk_env_extend[OF env Tden])
  have SL: "has_ptype (\<sigma> # \<Gamma>) (pshift ?L) (\<sigma> \<rightarrow>\<^sub>o \<tau>)"
    by (rule pshift_preserves_typing[OF L])
  have zero: "has_ptype (\<sigma> # \<Gamma>) (PVar 0) \<sigma>"
    by (rule has_ptype.PVar) simp
  have redex: "has_ptype (\<sigma> # \<Gamma>) (PApp (pshift ?L) (PVar 0)) \<tau>"
    by (rule has_ptype.PApp[OF SL zero])
  have step: "pcompatible_step pbeta_contract (PApp (pshift ?L) (PVar 0)) A"
  proof -
    have "pcompatible_step pbeta_contract
      (PApp (PLam \<sigma> (prename (lift_ren Suc) A)) (PVar 0))
      (psubst0 (PVar 0) (prename (lift_ren Suc) A))"
      by (intro pcompatible_step.root pbeta_contract.beta)
    then show ?thesis by (simp add: pshift_def pbbk_beta_slot_restore)
  qed
  have sigleft: "pterm_in_signature signature (PApp (pshift ?L) (PVar 0))"
    using sigL by (simp add: pshift_def)
  have conv: "pbeta_eta_equiv_in_signature signature (\<sigma> # \<Gamma>) \<tau>
      (PApp (pshift ?L) (PVar 0)) A"
    by (rule pbeta_eta_equiv_in_signature.Beta[OF redex body sigleft sigA step])
  have sigright: "pterm_in_signature signature (PApp ?L T)" using sigL sigT by simp
  have beta_left: "denote ?h (PApp (pshift ?L) (PVar 0)) = denote ?h A"
    by (rule denote_beta_eta[OF conv sigleft sigA extended])
  have same_function: "denote ?h (pshift ?L) = denote g ?L"
    by (rule pbbk_shift_assignment[OF L sigL env Tden])
  have same_argument: "denote ?h (PVar 0) = denote g T"
  proof -
    have variable: "denote ?h (PVar 0) = ?h 0"
      by (rule denote_var[OF lookup_Cons_0 extended])
    show ?thesis using variable by (simp only: pbbk_extend_zero)
  qed
  have same_application: "denote ?h (PApp (pshift ?L) (PVar 0)) = denote g (PApp ?L T)"
    by (rule denote_application_cong
      [OF SL zero L arg sigleft sigright extended env same_function same_argument])
  have beta_right: "denote g (PApp ?L T) = denote g (psubst0 T A)"
    by (rule pbbk_denote_beta[OF body arg sigA sigT env])
  have "denote ?h A = denote ?h (PApp (pshift ?L) (PVar 0))" by (rule sym[OF beta_left])
  also have "... = denote g (PApp ?L T)" by (rule same_application)
  also have "... = denote g (psubst0 T A)" by (rule beta_right)
  finally show ?thesis .
qed

text \<open>
  ⟦A[B/v]⟧ᴹᵍ = ⟦A⟧ᴹʰ, where h = g[v ↦ ⟦B⟧ᴹᵍ].
  Evaluate A after assigning v the denotation of B.

  Isabelle representation: pbbk_one_binder uses pbbk_extend, psubst0,
  contextual β conversion, and denote_rename.  Its hypotheses retain typing,
  signature membership, and the typed environment.

  Status: covers open bodies and arbitrary name carriers.  H_Soundness uses
  this law in the separate soundness proof; model existence, Henkin closure,
  and completeness are not conclusions of this file.
\<close>

end
end
