theory Bacon_Book_Lambda_I_Conversion
  imports Bacon_Book_Lambda_I_Calculus
begin

section \<open>Internal βη-conversion with α inside the λI fragment\<close>

text \<open>
  Conversion between λI terms is generated by immediate compatible β and η
  steps in either direction whose endpoints are λI terms of one type in the
  declared signature. Every intermediate node is therefore a λI term. This
  is the relation used by the λI model clause (Definition 14.13 read through
  Proposition 9.1): it is finer than raw ambient βη-equivalence, and the
  claim that every raw βη-equivalence between λI endpoints is an internal
  chain (which needs a typed Church–Rosser argument) is not made here.

  The proof that α-conversion is internal mirrors the full-language proof
  named_alpha_implies_beta_eta step by step, recording relevance: the
  η-expansion λy.((λx.M) y) of a relevant abstraction is relevant, its
  β-reduct λy.M[y/x] is relevant, and the substitution/swap alignment is
  proved by structural recursion inside the fragment.
\<close>

abbreviation book_LI :: "'c ssignature \<Rightarrow> sgcontext \<Rightarrow> otype \<Rightarrow> 'c book_named_term set" where
  "book_LI \<Sigma> G \<tau> \<equiv> book_lambda_I_terms book_minimal_logical_type UNIV \<Sigma> G \<tau>"

lemma book_LI_I:
  "book_in_language book_minimal_logical_type UNIV \<Sigma> G A \<tau> \<Longrightarrow> book_lambda_I A \<Longrightarrow> A \<in> book_LI \<Sigma> G \<tau>"
  by (rule book_lambda_I_termsI)

lemma book_LI_App:
  assumes head: "F \<in> book_LI \<Sigma> G (Arr \<sigma> \<tau>)" and argument: "A \<in> book_LI \<Sigma> G \<sigma>"
  shows "NApp F A \<in> book_LI \<Sigma> G \<tau>"
  by (rule book_LI_I[OF book_language_App[OF book_lambda_I_terms_language[OF head]
    book_lambda_I_terms_language[OF argument]]])
    (simp add: book_lambda_I_terms_relevant[OF head] book_lambda_I_terms_relevant[OF argument])

lemma book_LI_Lam:
  assumes body: "A \<in> book_LI \<Sigma> G \<tau>" and occurs: "n \<in> named_fv A"
  shows "NLam n A \<in> book_LI \<Sigma> G (Arr (G n) \<tau>)"
  by (rule book_LI_I[OF book_language_Lam[OF book_lambda_I_terms_language[OF body]]])
    (simp add: book_lambda_I_terms_relevant[OF body] occurs)

lemma book_LI_Lam_parts:
  assumes member: "NLam n A \<in> book_LI \<Sigma> G \<tau>"
  obtains \<rho> where "\<tau> = Arr (G n) \<rho>" and "A \<in> book_LI \<Sigma> G \<rho>" and "n \<in> named_fv A"
proof -
  obtain \<rho> where ty: "\<tau> = Arr (G n) \<rho>"
    and body: "book_in_language book_minimal_logical_type UNIV \<Sigma> G A \<rho>"
    by (rule book_language_Lam_obtain[OF book_lambda_I_terms_language[OF member]]; rule that; assumption)
  have relevant: "book_lambda_I A" and occurs: "n \<in> named_fv A"
    using book_lambda_I_terms_relevant[OF member] by simp_all
  show thesis by (rule that[OF ty book_LI_I[OF body relevant] occurs])
qed

lemma book_LI_App_parts:
  assumes member: "NApp F A \<in> book_LI \<Sigma> G \<tau>"
  obtains \<sigma> where "F \<in> book_LI \<Sigma> G (Arr \<sigma> \<tau>)" and "A \<in> book_LI \<Sigma> G \<sigma>"
proof -
  obtain \<sigma> where fl: "book_in_language book_minimal_logical_type UNIV \<Sigma> G F (Arr \<sigma> \<tau>)"
    and al: "book_in_language book_minimal_logical_type UNIV \<Sigma> G A \<sigma>"
    by (rule book_language_App_obtain[OF book_lambda_I_terms_language[OF member]]; rule that; assumption)
  have fr: "book_lambda_I F" and ar: "book_lambda_I A"
    using book_lambda_I_terms_relevant[OF member] by simp_all
  show thesis by (rule that[OF book_LI_I[OF fl fr] book_LI_I[OF al ar]])
qed

lemma book_LI_Var:
  "NVar n \<in> book_LI \<Sigma> G (G n)"
  by (rule book_LI_I) (simp_all add: book_language_var_iff)

subsection \<open>The internal conversion relation\<close>

inductive book_lambda_I_conv ::
  "'c ssignature \<Rightarrow> sgcontext \<Rightarrow> otype \<Rightarrow> 'c book_named_term \<Rightarrow> 'c book_named_term \<Rightarrow> bool"
  for \<Sigma> :: "'c ssignature" and G :: sgcontext where
  Refl: "A \<in> book_LI \<Sigma> G \<tau> \<Longrightarrow> book_lambda_I_conv \<Sigma> G \<tau> A A"
| Beta: "A \<in> book_LI \<Sigma> G \<tau> \<Longrightarrow> B \<in> book_LI \<Sigma> G \<tau> \<Longrightarrow>
    named_compatible_step named_beta_contract A B \<Longrightarrow> book_lambda_I_conv \<Sigma> G \<tau> A B"
| Eta: "A \<in> book_LI \<Sigma> G \<tau> \<Longrightarrow> B \<in> book_LI \<Sigma> G \<tau> \<Longrightarrow>
    named_compatible_step named_eta_contract A B \<Longrightarrow> book_lambda_I_conv \<Sigma> G \<tau> A B"
| Sym: "book_lambda_I_conv \<Sigma> G \<tau> A B \<Longrightarrow> book_lambda_I_conv \<Sigma> G \<tau> B A"
| Trans: "book_lambda_I_conv \<Sigma> G \<tau> A B \<Longrightarrow> book_lambda_I_conv \<Sigma> G \<tau> B C \<Longrightarrow>
    book_lambda_I_conv \<Sigma> G \<tau> A C"

lemma book_lambda_I_conv_terms:
  assumes conversion: "book_lambda_I_conv \<Sigma> G \<tau> A B"
  shows "A \<in> book_LI \<Sigma> G \<tau> \<and> B \<in> book_LI \<Sigma> G \<tau>"
  using conversion by (induction rule: book_lambda_I_conv.induct) blast+

theorem book_lambda_I_conv_in_language:
  assumes conversion: "book_lambda_I_conv \<Sigma> G \<tau> A B"
  shows "named_beta_eta_in_language book_minimal_logical_type \<Sigma> G \<tau> A B"
  using conversion
proof (induction rule: book_lambda_I_conv.induct)
  case (Refl A \<tau>)
  show ?case by (rule named_beta_eta_in_language.Refl[OF book_language_named[OF book_lambda_I_terms_language[OF Refl.hyps]]])
next
  case (Beta A \<tau> B)
  show ?case by (rule named_beta_eta_in_language.Beta[OF book_language_named[OF book_lambda_I_terms_language[OF Beta.hyps(1)]]
    book_language_named[OF book_lambda_I_terms_language[OF Beta.hyps(2)]] Beta.hyps(3)])
next
  case (Eta A \<tau> B)
  show ?case by (rule named_beta_eta_in_language.Eta[OF book_language_named[OF book_lambda_I_terms_language[OF Eta.hyps(1)]]
    book_language_named[OF book_lambda_I_terms_language[OF Eta.hyps(2)]] Eta.hyps(3)])
next
  case Sym
  show ?case by (rule named_beta_eta_in_language.Sym[OF Sym.IH])
next
  case Trans
  show ?case by (rule named_beta_eta_in_language.Trans[OF Trans.IH])
qed

corollary book_lambda_I_conv_raw:
  assumes conversion: "book_lambda_I_conv \<Sigma> G \<tau> A B"
  shows "named_raw_beta_eta book_minimal_logical_type G \<tau> A B"
  by (rule named_conversion_to_raw[OF book_lambda_I_conv_in_language[OF conversion]])

subsection \<open>Free variables are preserved along internal conversion\<close>

lemma book_lambda_I_exact_beta_root:
  assumes step: "named_beta_contract A B" and al: "book_lambda_I A"
  shows "book_lambda_I B \<and> named_fv B = named_fv A"
  using step al
proof (induction rule: named_beta_contract.induct)
  case (beta B x A)
  have al': "book_lambda_I A" and occurs: "x \<in> named_fv A" and bl: "book_lambda_I B"
    using beta.prems by simp_all
  show ?case
    by (rule conjI[OF book_lambda_I_subst[OF al' bl beta.hyps] book_lambda_I_beta_fv[OF occurs beta.hyps]])
qed

lemma book_lambda_I_beta_step:
  assumes step: "named_compatible_step named_beta_contract A B" and al: "book_lambda_I A"
  shows "book_lambda_I B \<and> named_fv B = named_fv A"
  by (rule book_lambda_I_compatible_step[OF book_lambda_I_exact_beta_root step al])

lemma book_lambda_I_eta_step:
  assumes step: "named_compatible_step named_eta_contract A B" and al: "book_lambda_I A"
  shows "book_lambda_I B \<and> named_fv B = named_fv A"
  by (rule book_lambda_I_compatible_step[OF book_lambda_I_eta_root step al])

theorem book_lambda_I_conv_fv:
  assumes conversion: "book_lambda_I_conv \<Sigma> G \<tau> A B"
  shows "named_fv A = named_fv B"
  using conversion
proof (induction rule: book_lambda_I_conv.induct)
  case Refl
  show ?case by (rule refl)
next
  case (Beta A \<tau> B)
  show ?case by (rule conjunct2[OF book_lambda_I_beta_step[OF Beta.hyps(3) book_lambda_I_terms_relevant[OF Beta.hyps(1)]], symmetric])
next
  case (Eta A \<tau> B)
  show ?case by (rule conjunct2[OF book_lambda_I_eta_step[OF Eta.hyps(3) book_lambda_I_terms_relevant[OF Eta.hyps(1)]], symmetric])
next
  case Sym
  show ?case by (rule Sym.IH[symmetric])
next
  case Trans
  show ?case by (rule trans[OF Trans.IH])
qed

subsection \<open>Context lifting\<close>

lemma book_lambda_I_conv_App_left_general:
  assumes conversion: "book_lambda_I_conv \<Sigma> G \<rho> F H" and ty: "\<rho> = Arr \<sigma> \<tau>"
    and argument: "A \<in> book_LI \<Sigma> G \<sigma>"
  shows "book_lambda_I_conv \<Sigma> G \<tau> (NApp F A) (NApp H A)"
  using conversion ty
proof (induction rule: book_lambda_I_conv.induct)
  case (Refl F \<rho>)
  show ?case by (rule book_lambda_I_conv.Refl[OF book_LI_App[OF Refl.hyps[unfolded Refl.prems] argument]])
next
  case (Beta F \<rho> H)
  show ?case by (rule book_lambda_I_conv.Beta[OF book_LI_App[OF Beta.hyps(1)[unfolded Beta.prems] argument]
    book_LI_App[OF Beta.hyps(2)[unfolded Beta.prems] argument] named_compatible_step.App_left[OF Beta.hyps(3)]])
next
  case (Eta F \<rho> H)
  show ?case by (rule book_lambda_I_conv.Eta[OF book_LI_App[OF Eta.hyps(1)[unfolded Eta.prems] argument]
    book_LI_App[OF Eta.hyps(2)[unfolded Eta.prems] argument] named_compatible_step.App_left[OF Eta.hyps(3)]])
next
  case Sym
  show ?case by (rule book_lambda_I_conv.Sym[OF Sym.IH[OF Sym.prems]])
next
  case Trans
  show ?case by (rule book_lambda_I_conv.Trans[OF Trans.IH(1)[OF Trans.prems] Trans.IH(2)[OF Trans.prems]])
qed

lemma book_lambda_I_conv_App_left:
  assumes conversion: "book_lambda_I_conv \<Sigma> G (Arr \<sigma> \<tau>) F H"
    and argument: "A \<in> book_LI \<Sigma> G \<sigma>"
  shows "book_lambda_I_conv \<Sigma> G \<tau> (NApp F A) (NApp H A)"
  by (rule book_lambda_I_conv_App_left_general[OF conversion refl argument])

lemma book_lambda_I_conv_App_right_general:
  assumes conversion: "book_lambda_I_conv \<Sigma> G \<rho> A B" and ty: "\<rho> = \<sigma>"
    and head: "F \<in> book_LI \<Sigma> G (Arr \<sigma> \<tau>)"
  shows "book_lambda_I_conv \<Sigma> G \<tau> (NApp F A) (NApp F B)"
  using conversion ty
proof (induction rule: book_lambda_I_conv.induct)
  case (Refl A \<rho>)
  show ?case by (rule book_lambda_I_conv.Refl[OF book_LI_App[OF head Refl.hyps[unfolded Refl.prems]]])
next
  case (Beta A \<rho> B)
  show ?case by (rule book_lambda_I_conv.Beta[OF book_LI_App[OF head Beta.hyps(1)[unfolded Beta.prems]]
    book_LI_App[OF head Beta.hyps(2)[unfolded Beta.prems]] named_compatible_step.App_right[OF Beta.hyps(3)]])
next
  case (Eta A \<rho> B)
  show ?case by (rule book_lambda_I_conv.Eta[OF book_LI_App[OF head Eta.hyps(1)[unfolded Eta.prems]]
    book_LI_App[OF head Eta.hyps(2)[unfolded Eta.prems]] named_compatible_step.App_right[OF Eta.hyps(3)]])
next
  case Sym
  show ?case by (rule book_lambda_I_conv.Sym[OF Sym.IH[OF Sym.prems]])
next
  case Trans
  show ?case by (rule book_lambda_I_conv.Trans[OF Trans.IH(1)[OF Trans.prems] Trans.IH(2)[OF Trans.prems]])
qed

lemma book_lambda_I_conv_App_right:
  assumes head: "F \<in> book_LI \<Sigma> G (Arr \<sigma> \<tau>)"
    and conversion: "book_lambda_I_conv \<Sigma> G \<sigma> A B"
  shows "book_lambda_I_conv \<Sigma> G \<tau> (NApp F A) (NApp F B)"
  by (rule book_lambda_I_conv_App_right_general[OF conversion refl head])

lemma book_lambda_I_conv_App:
  assumes head: "book_lambda_I_conv \<Sigma> G (Arr \<sigma> \<tau>) F H"
    and argument: "book_lambda_I_conv \<Sigma> G \<sigma> A B"
  shows "book_lambda_I_conv \<Sigma> G \<tau> (NApp F A) (NApp H B)"
proof -
  have am: "A \<in> book_LI \<Sigma> G \<sigma>" by (rule conjunct1[OF book_lambda_I_conv_terms[OF argument]])
  have hm: "H \<in> book_LI \<Sigma> G (Arr \<sigma> \<tau>)" by (rule conjunct2[OF book_lambda_I_conv_terms[OF head]])
  show ?thesis by (rule book_lambda_I_conv.Trans[OF book_lambda_I_conv_App_left[OF head am]
    book_lambda_I_conv_App_right[OF hm argument]])
qed

lemma book_lambda_I_conv_Lam:
  assumes conversion: "book_lambda_I_conv \<Sigma> G \<tau> A B" and occurs: "n \<in> named_fv A"
  shows "book_lambda_I_conv \<Sigma> G (Arr (G n) \<tau>) (NLam n A) (NLam n B)"
  using conversion occurs
proof (induction rule: book_lambda_I_conv.induct)
  case (Refl A \<rho>)
  show ?case by (rule book_lambda_I_conv.Refl[OF book_LI_Lam[OF Refl.hyps Refl.prems]])
next
  case (Beta A \<rho> B)
  have fv: "named_fv B = named_fv A"
    by (rule conjunct2[OF book_lambda_I_beta_step[OF Beta.hyps(3) book_lambda_I_terms_relevant[OF Beta.hyps(1)]]])
  have occurs': "n \<in> named_fv B" using Beta.prems by (simp only: fv)
  show ?case by (rule book_lambda_I_conv.Beta[OF book_LI_Lam[OF Beta.hyps(1) Beta.prems]
    book_LI_Lam[OF Beta.hyps(2) occurs'] named_compatible_step.Lam_body[OF Beta.hyps(3)]])
next
  case (Eta A \<rho> B)
  have fv: "named_fv B = named_fv A"
    by (rule conjunct2[OF book_lambda_I_eta_step[OF Eta.hyps(3) book_lambda_I_terms_relevant[OF Eta.hyps(1)]]])
  have occurs': "n \<in> named_fv B" using Eta.prems by (simp only: fv)
  show ?case by (rule book_lambda_I_conv.Eta[OF book_LI_Lam[OF Eta.hyps(1) Eta.prems]
    book_LI_Lam[OF Eta.hyps(2) occurs'] named_compatible_step.Lam_body[OF Eta.hyps(3)]])
next
  case (Sym \<rho> A B)
  have occurs': "n \<in> named_fv A" using Sym.prems by (simp only: book_lambda_I_conv_fv[OF Sym.hyps])
  show ?case by (rule book_lambda_I_conv.Sym[OF Sym.IH[OF occurs']])
next
  case (Trans \<rho> A B C)
  have occurs': "n \<in> named_fv B" using Trans.prems by (simp only: book_lambda_I_conv_fv[OF Trans.hyps(1)])
  show ?case by (rule book_lambda_I_conv.Trans[OF Trans.IH(1)[OF Trans.prems] Trans.IH(2)[OF occurs']])
qed

subsection \<open>Renaming a binder is an internal conversion\<close>

lemma book_lambda_I_binder_literal_rename:
  assumes body: "A \<in> book_LI \<Sigma> G \<tau>" and occurs: "x \<in> named_fv A"
    and same: "G x = G y" and fresh: "y \<notin> named_vars A"
  shows "book_lambda_I_conv \<Sigma> G (Arr (G x) \<tau>) (NLam x A) (NLam y (named_subst x (NVar y) A))"
proof -
  let ?F = "NLam x A"
  let ?R = "NApp ?F (NVar y)"
  let ?S = "named_subst x (NVar y) A"
  have variable: "NVar y \<in> book_LI \<Sigma> G (G x)" using book_LI_Var[of y \<Sigma> G] by (simp only: same)
  have fm: "?F \<in> book_LI \<Sigma> G (Arr (G x) \<tau>)" by (rule book_LI_Lam[OF body occurs])
  have redex: "?R \<in> book_LI \<Sigma> G \<tau>" by (rule book_LI_App[OF fm variable])
  have y_free: "y \<in> named_fv ?R" by simp
  have expanded: "NLam y ?R \<in> book_LI \<Sigma> G (Arr (G x) \<tau>)"
    using book_LI_Lam[OF redex y_free] by (simp only: same)
  have free_for: "named_free_for (NVar y) x A" by (rule named_fresh_variable_free_for[OF fresh])
  have substituted_language: "book_in_language book_minimal_logical_type UNIV \<Sigma> G ?S \<tau>"
    by (rule book_variable_subst_language[OF book_lambda_I_terms_language[OF body]
      book_lambda_I_terms_language[OF variable]])
  have substituted_relevant: "book_lambda_I ?S"
    by (rule book_lambda_I_subst[OF book_lambda_I_terms_relevant[OF body] _ free_for]) simp
  have substituted: "?S \<in> book_LI \<Sigma> G \<tau>" by (rule book_LI_I[OF substituted_language substituted_relevant])
  have fv: "named_fv ?S = (named_fv A - {x}) \<union> {y}"
    by (simp add: named_subst_fv_exact[OF free_for] occurs)
  have y_in: "y \<in> named_fv ?S" by (simp add: fv)
  have contracted: "NLam y ?S \<in> book_LI \<Sigma> G (Arr (G x) \<tau>)"
    using book_LI_Lam[OF substituted y_in] by (simp only: same)
  have not_free: "y \<notin> named_fv ?F" using fresh named_fv_subset_vars[where A=A] by auto
  have eta_root: "named_eta_contract (NLam y ?R) ?F" by (rule named_eta_contract.eta[OF not_free])
  have eta_step: "named_compatible_step named_eta_contract (NLam y ?R) ?F"
    by (rule named_compatible_step.root[where R=named_eta_contract and M="NLam y ?R" and N="?F", OF eta_root])
  have eta: "book_lambda_I_conv \<Sigma> G (Arr (G x) \<tau>) (NLam y ?R) ?F"
    by (rule book_lambda_I_conv.Eta[OF expanded fm eta_step])
  have beta_root: "named_beta_contract ?R ?S" by (rule named_beta_contract.beta[OF free_for])
  have beta_step: "named_compatible_step named_beta_contract ?R ?S"
    by (rule named_compatible_step.root[where R=named_beta_contract and M="?R" and N="?S", OF beta_root])
  have beta: "book_lambda_I_conv \<Sigma> G \<tau> ?R ?S" by (rule book_lambda_I_conv.Beta[OF redex substituted beta_step])
  have under_binder: "book_lambda_I_conv \<Sigma> G (Arr (G x) \<tau>) (NLam y ?R) (NLam y ?S)"
    using book_lambda_I_conv_Lam[OF beta y_free] by (simp only: same)
  show ?thesis by (rule book_lambda_I_conv.Trans[OF book_lambda_I_conv.Sym[OF eta] under_binder])
qed

lemma book_LI_swap:
  assumes member: "A \<in> book_LI \<Sigma> G \<tau>" and same: "G x = G y"
  shows "named_swap x y A \<in> book_LI \<Sigma> G \<tau>"
proof (rule book_LI_I)
  show "book_in_language book_minimal_logical_type UNIV \<Sigma> G (named_swap x y A) \<tau>"
    by (simp only: book_language_UNIV; rule named_conversion_swap_language[OF
      iffD1[OF book_language_UNIV book_lambda_I_terms_language[OF member]] same])
  show "book_lambda_I (named_swap x y A)" by (rule book_lambda_I_swap[OF book_lambda_I_terms_relevant[OF member]])
qed

theorem book_lambda_I_subst_swap_conv:
  assumes member: "A \<in> book_LI \<Sigma> G \<tau>" and same: "G x = G y" and fresh: "y \<notin> named_vars A"
  shows "book_lambda_I_conv \<Sigma> G \<tau> (named_subst x (NVar y) A) (named_swap x y A)"
  using member same fresh
proof (induction A arbitrary: x y \<tau>)
  case (NVar n)
  have same_term: "named_subst x (NVar y) (NVar n) = named_swap x y (NVar n)"
    using NVar.prems(3) by (auto simp: named_swap_index_def)
  show ?case by (simp only: same_term; rule book_lambda_I_conv.Refl[OF book_LI_swap[OF NVar.prems(1,2)]])
next
  case (NConst c \<sigma>)
  show ?case by (simp only: named_subst.simps named_swap.simps; rule book_lambda_I_conv.Refl[OF NConst.prems(1)])
next
  case (NLogical l)
  show ?case by (simp only: named_subst.simps named_swap.simps; rule book_lambda_I_conv.Refl[OF NLogical.prems(1)])
next
  case (NApp F A)
  obtain \<sigma> where fm: "F \<in> book_LI \<Sigma> G (Arr \<sigma> \<tau>)" and am: "A \<in> book_LI \<Sigma> G \<sigma>"
    by (rule book_LI_App_parts[OF NApp.prems(1)])
  have fresh_F: "y \<notin> named_vars F" and fresh_A: "y \<notin> named_vars A" using NApp.prems(3) by simp_all
  have fc: "book_lambda_I_conv \<Sigma> G (Arr \<sigma> \<tau>) (named_subst x (NVar y) F) (named_swap x y F)"
    by (rule NApp.IH(1)[OF fm NApp.prems(2) fresh_F])
  have ac: "book_lambda_I_conv \<Sigma> G \<sigma> (named_subst x (NVar y) A) (named_swap x y A)"
    by (rule NApp.IH(2)[OF am NApp.prems(2) fresh_A])
  show ?case by (simp only: named_subst.simps named_swap.simps; rule book_lambda_I_conv_App[OF fc ac])
next
  case (NLam n A)
  obtain \<rho> where ty: "\<tau> = Arr (G n) \<rho>" and body: "A \<in> book_LI \<Sigma> G \<rho>" and occurs: "n \<in> named_fv A"
    by (rule book_LI_Lam_parts[OF NLam.prems(1)])
  have fresh_body: "y \<notin> named_vars A" and not_y: "n \<noteq> y" using NLam.prems(3) by auto
  have aligned: "book_lambda_I_conv \<Sigma> G \<rho> (named_subst x (NVar y) A) (named_swap x y A)"
    by (rule NLam.IH[OF body NLam.prems(2) fresh_body])
  show ?case
  proof (cases "n = x")
    case True
    have literal: "book_lambda_I_conv \<Sigma> G (Arr (G x) \<rho>) (NLam x A) (NLam y (named_subst x (NVar y) A))"
      by (rule book_lambda_I_binder_literal_rename[OF body _ NLam.prems(2) fresh_body]) (simp only: occurs[unfolded True])
    have free_for: "named_free_for (NVar y) x A" by (rule named_fresh_variable_free_for[OF fresh_body])
    have y_in: "y \<in> named_fv (named_subst x (NVar y) A)"
      using occurs by (simp add: named_subst_fv_exact[OF free_for] True)
    have under: "book_lambda_I_conv \<Sigma> G (Arr (G x) \<rho>) (NLam y (named_subst x (NVar y) A)) (NLam y (named_swap x y A))"
      using book_lambda_I_conv_Lam[OF aligned y_in] by (simp only: NLam.prems(2))
    have shadow: "book_lambda_I_conv \<Sigma> G (Arr (G x) \<rho>) (NLam x A) (NLam y (named_swap x y A))"
      by (rule book_lambda_I_conv.Trans[OF literal under])
    show ?thesis using shadow by (simp add: ty True)
  next
    case False
    have binder_index: "named_swap_index x y n = n" by (simp only: named_swap_index_def False not_y if_False)
    have free_for: "named_free_for (NVar y) x A" by (rule named_fresh_variable_free_for[OF fresh_body])
    have n_in: "n \<in> named_fv (named_subst x (NVar y) A)"
      using occurs False by (simp add: named_subst_fv_exact[OF free_for])
    have under: "book_lambda_I_conv \<Sigma> G (Arr (G n) \<rho>) (NLam n (named_subst x (NVar y) A)) (NLam n (named_swap x y A))"
      by (rule book_lambda_I_conv_Lam[OF aligned n_in])
    show ?thesis using under by (simp only: ty named_subst.simps False if_False named_swap.simps binder_index)
  qed
qed

corollary book_lambda_I_fresh_binder_conv:
  assumes member: "NLam x A \<in> book_LI \<Sigma> G \<tau>" and same: "G x = G y" and fresh: "y \<notin> named_vars A"
  shows "book_lambda_I_conv \<Sigma> G \<tau> (NLam x A) (NLam y (named_swap x y A))"
proof -
  obtain \<rho> where ty: "\<tau> = Arr (G x) \<rho>" and body: "A \<in> book_LI \<Sigma> G \<rho>" and occurs: "x \<in> named_fv A"
    by (rule book_LI_Lam_parts[OF member])
  have literal: "book_lambda_I_conv \<Sigma> G (Arr (G x) \<rho>) (NLam x A) (NLam y (named_subst x (NVar y) A))"
    by (rule book_lambda_I_binder_literal_rename[OF body occurs same fresh])
  have free_for: "named_free_for (NVar y) x A" by (rule named_fresh_variable_free_for[OF fresh])
  have y_in: "y \<in> named_fv (named_subst x (NVar y) A)"
    using occurs by (simp add: named_subst_fv_exact[OF free_for])
  have under: "book_lambda_I_conv \<Sigma> G (Arr (G x) \<rho>) (NLam y (named_subst x (NVar y) A)) (NLam y (named_swap x y A))"
    using book_lambda_I_conv_Lam[OF book_lambda_I_subst_swap_conv[OF body same fresh] y_in] by (simp only: same)
  show ?thesis unfolding ty by (rule book_lambda_I_conv.Trans[OF literal under])
qed

theorem book_lambda_I_alpha_conv:
  assumes alpha: "named_alpha G A B" and member: "A \<in> book_LI \<Sigma> G \<tau>"
  shows "book_lambda_I_conv \<Sigma> G \<tau> A B"
  using alpha member
proof (induction arbitrary: \<tau> rule: named_alpha.induct)
  case (Refl A)
  show ?case by (rule book_lambda_I_conv.Refl[OF Refl.prems])
next
  case (Fresh_Binder x y A)
  show ?case by (rule book_lambda_I_fresh_binder_conv[OF Fresh_Binder.prems Fresh_Binder.hyps])
next
  case (App F H A B)
  obtain \<sigma> where fm: "F \<in> book_LI \<Sigma> G (Arr \<sigma> \<tau>)" and am: "A \<in> book_LI \<Sigma> G \<sigma>"
    by (rule book_LI_App_parts[OF App.prems])
  show ?case by (rule book_lambda_I_conv_App[OF App.IH(1)[OF fm] App.IH(2)[OF am]])
next
  case (Lam A B n)
  obtain \<rho> where ty: "\<tau> = Arr (G n) \<rho>" and body: "A \<in> book_LI \<Sigma> G \<rho>" and occurs: "n \<in> named_fv A"
    by (rule book_LI_Lam_parts[OF Lam.prems])
  show ?case unfolding ty by (rule book_lambda_I_conv_Lam[OF Lam.IH[OF body] occurs])
next
  case (Sym A B)
  have language: "book_in_language book_minimal_logical_type UNIV \<Sigma> G A \<tau>"
    by (simp only: book_language_UNIV; rule iffD2[OF named_alpha_language_iff[OF Sym.hyps]
      iffD1[OF book_language_UNIV book_lambda_I_terms_language[OF Sym.prems]]])
  have relevant: "book_lambda_I A"
    by (simp only: book_lambda_I_alpha_iff[OF Sym.hyps]; rule book_lambda_I_terms_relevant[OF Sym.prems])
  show ?case by (rule book_lambda_I_conv.Sym[OF Sym.IH[OF book_LI_I[OF language relevant]]])
next
  case (Trans A B C)
  have first: "book_lambda_I_conv \<Sigma> G \<tau> A B" by (rule Trans.IH(1)[OF Trans.prems])
  have middle: "B \<in> book_LI \<Sigma> G \<tau>" by (rule conjunct2[OF book_lambda_I_conv_terms[OF first]])
  show ?case by (rule book_lambda_I_conv.Trans[OF first Trans.IH(2)[OF middle]])
qed

subsection \<open>Propositional lemmas and derivability transport\<close>

lemma book_lambda_I_imp_refl:
  assumes al: "book_lambda_I_formula \<Sigma> G A"
  shows "book_lambda_I_derivable \<Sigma> G S (book_imp A A)"
proof -
  let ?AA = "book_imp A A"
  have aa: "book_lambda_I_formula \<Sigma> G ?AA" using al by (simp add: book_lambda_I_imp_formula)
  have first: "book_lambda_I_derivable \<Sigma> G S (book_imp (book_imp A (book_imp ?AA A)) (book_imp (book_imp A ?AA) ?AA))"
    by (rule book_lambda_I_derivable.PC2[OF al aa al])
  have second: "book_lambda_I_derivable \<Sigma> G S (book_imp A (book_imp ?AA A))"
    by (rule book_lambda_I_derivable.PC1[OF al aa])
  have third: "book_lambda_I_derivable \<Sigma> G S (book_imp (book_imp A ?AA) ?AA)"
    by (rule book_lambda_I_derivable.MP[OF second first]) (simp add: book_lambda_I_imp_formula al aa)
  have fourth: "book_lambda_I_derivable \<Sigma> G S (book_imp A ?AA)"
    by (rule book_lambda_I_derivable.PC1[OF al al])
  show ?thesis by (rule book_lambda_I_derivable.MP[OF fourth third aa])
qed

lemma book_lambda_I_imp_trans:
  assumes ab: "book_lambda_I_derivable \<Sigma> G S (book_imp A B)"
    and bc: "book_lambda_I_derivable \<Sigma> G S (book_imp B C)"
    and al: "book_lambda_I_formula \<Sigma> G A" and bl: "book_lambda_I_formula \<Sigma> G B"
    and cl: "book_lambda_I_formula \<Sigma> G C"
  shows "book_lambda_I_derivable \<Sigma> G S (book_imp A C)"
proof -
  have lift: "book_lambda_I_derivable \<Sigma> G S (book_imp (book_imp B C) (book_imp A (book_imp B C)))"
    by (rule book_lambda_I_derivable.PC1) (simp_all add: book_lambda_I_imp_formula bl cl al)
  have nested: "book_lambda_I_derivable \<Sigma> G S (book_imp A (book_imp B C))"
    by (rule book_lambda_I_derivable.MP[OF bc lift]) (simp add: book_lambda_I_imp_formula al bl cl)
  have distribute: "book_lambda_I_derivable \<Sigma> G S
    (book_imp (book_imp A (book_imp B C)) (book_imp (book_imp A B) (book_imp A C)))"
    by (rule book_lambda_I_derivable.PC2[OF al bl cl])
  have partial: "book_lambda_I_derivable \<Sigma> G S (book_imp (book_imp A B) (book_imp A C))"
    by (rule book_lambda_I_derivable.MP[OF nested distribute]) (simp add: book_lambda_I_imp_formula al bl cl)
  show ?thesis by (rule book_lambda_I_derivable.MP[OF ab partial]) (simp add: book_lambda_I_imp_formula al cl)
qed

lemma book_lambda_I_conv_derivable_pair_general:
  assumes conversion: "book_lambda_I_conv \<Sigma> G \<tau> A B" and ty: "\<tau> = Prop"
  shows "book_lambda_I_derivable \<Sigma> G S (book_imp A B) \<and> book_lambda_I_derivable \<Sigma> G S (book_imp B A)"
  using conversion ty
proof (induction rule: book_lambda_I_conv.induct)
  case (Refl A \<tau>)
  have al: "book_lambda_I_formula \<Sigma> G A" using Refl.hyps[unfolded Refl.prems] by (simp only: book_lambda_I_formula_terms)
  show ?case using book_lambda_I_imp_refl[OF al] by simp
next
  case (Beta A \<tau> B)
  have al: "book_lambda_I_formula \<Sigma> G A" and bl: "book_lambda_I_formula \<Sigma> G B"
    using Beta.hyps(1,2)[unfolded Beta.prems] by (simp_all only: book_lambda_I_formula_terms)
  show ?case
    by (rule conjI[OF book_lambda_I_derivable.Beta[OF al bl disjI1[OF Beta.hyps(3)]]
      book_lambda_I_derivable.Beta[OF bl al disjI2[OF Beta.hyps(3)]]])
next
  case (Eta A \<tau> B)
  have al: "book_lambda_I_formula \<Sigma> G A" and bl: "book_lambda_I_formula \<Sigma> G B"
    using Eta.hyps(1,2)[unfolded Eta.prems] by (simp_all only: book_lambda_I_formula_terms)
  show ?case
    by (rule conjI[OF book_lambda_I_derivable.Eta[OF al bl disjI1[OF Eta.hyps(3)]]
      book_lambda_I_derivable.Eta[OF bl al disjI2[OF Eta.hyps(3)]]])
next
  case Sym
  show ?case using Sym.IH[OF Sym.prems] by simp
next
  case (Trans \<tau> A B C)
  have al: "book_lambda_I_formula \<Sigma> G A" and bl: "book_lambda_I_formula \<Sigma> G B"
    and cl: "book_lambda_I_formula \<Sigma> G C"
    using book_lambda_I_conv_terms[OF Trans.hyps(1)] book_lambda_I_conv_terms[OF Trans.hyps(2)]
    unfolding Trans.prems by (simp_all only: book_lambda_I_formula_terms)
  show ?case
    by (rule conjI[OF book_lambda_I_imp_trans[OF conjunct1[OF Trans.IH(1)[OF Trans.prems]] conjunct1[OF Trans.IH(2)[OF Trans.prems]] al bl cl]
      book_lambda_I_imp_trans[OF conjunct2[OF Trans.IH(2)[OF Trans.prems]] conjunct2[OF Trans.IH(1)[OF Trans.prems]] cl bl al]])
qed

theorem book_lambda_I_conv_derivable_pair:
  assumes conversion: "book_lambda_I_conv \<Sigma> G Prop A B"
  shows "book_lambda_I_derivable \<Sigma> G S (book_imp A B) \<and> book_lambda_I_derivable \<Sigma> G S (book_imp B A)"
  by (rule book_lambda_I_conv_derivable_pair_general[OF conversion refl])

theorem book_lambda_I_conv_transport:
  assumes conversion: "book_lambda_I_conv \<Sigma> G Prop A B"
    and derivation: "book_lambda_I_derivable \<Sigma> G S A"
  shows "book_lambda_I_derivable \<Sigma> G S B"
proof -
  have bl: "book_lambda_I_formula \<Sigma> G B"
    using conjunct2[OF book_lambda_I_conv_terms[OF conversion]] by (simp only: book_lambda_I_formula_terms)
  show ?thesis by (rule book_lambda_I_derivable.MP[OF derivation conjunct1[OF book_lambda_I_conv_derivable_pair[OF conversion]] bl])
qed

theorem book_lambda_I_conv_derivable_iff:
  assumes conversion: "book_lambda_I_conv \<Sigma> G Prop A B"
  shows "book_lambda_I_derivable \<Sigma> G S A \<longleftrightarrow> book_lambda_I_derivable \<Sigma> G S B"
  by (rule iffI[OF book_lambda_I_conv_transport[OF conversion]
    book_lambda_I_conv_transport[OF book_lambda_I_conv.Sym[OF conversion]]])

corollary book_lambda_I_alpha_derivable_iff:
  assumes alpha: "named_alpha G A B" and al: "book_lambda_I_formula \<Sigma> G A"
  shows "book_lambda_I_derivable \<Sigma> G S A \<longleftrightarrow> book_lambda_I_derivable \<Sigma> G S B"
  by (rule book_lambda_I_conv_derivable_iff[OF book_lambda_I_alpha_conv[OF alpha
    iffD1[OF book_lambda_I_formula_terms al]]])

text \<open>
  Internal conversion transports derivability in both directions, and
  α-conversion is internal. Hence a maximal consistent set of the λI
  calculus is invariant under internal conversion, which is what the term
  model's valuation needs. Nothing here asserts that raw ambient
  βη-equivalence between λI endpoints is internal.
\<close>

end
